### ISSUE TITLE
Support deserialization into mutable collections

### ISSUE THREAD

**Issue by tokennyw** [json4s/json4s#138]
In the examples below using version 3.2.10, mutable collections serialize to the expected form but then fail to deserialize except into the equivalent immutable collection. While it's easy to work around for individual objects by deserializing into an immutable collection and then converting into mutable collections, it's harder when deserializing into a case class where mutable collections are potentially deep inside the field hierarchy.

```
scala> Serialization.write(mutable.Buffer(1, 2, 3))
res10: String = [1,2,3]

scala> Serialization.read[mutable.Buffer[Int]]("""[1, 2, 3]""")
java.lang.ClassCastException: scala.collection.immutable.$colon$colon cannot be cast to scala.collection.mutable.Buffer
  ... 63 elided

scala> Serialization.read[List[Int]]("""[1, 2, 3]""")
res12: List[Int] = List(1, 2, 3)

scala> Serialization.write(mutable.Set(1, 2, 3))
res13: String = [1,2,3]

scala> Serialization.read[mutable.Set[Int]]("""[1, 2, 3]""")
org.json4s.package$MappingException: Expected collection but got Set[int]
  at org.json4s.reflect.package$.fail(package.scala:96)
  at org.json4s.Extraction$CollectionBuilder.result(Extraction.scala:366)
  at org.json4s.Extraction$.extract(Extraction.scala:320)
  at org.json4s.Extraction$.extract(Extraction.scala:42)
  at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
  at org.json4s.jackson.Serialization$.read(Serialization.scala:50)
  ... 67 elided

scala> Serialization.read[Set[Int]]("""[1, 2, 3]""")
res15: Set[Int] = Set(1, 2, 3)

scala> Serialization.write(mutable.Map("a" -> 1, "b" -> 2, "c" -> 3))
res16: String = {"b":2,"a":1,"c":3}

scala> Serialization.read[mutable.Map[String, Int]]("""{"a": 1, "b": 2, "c": 3}""")
java.lang.ClassCastException: scala.collection.immutable.Map$Map3 cannot be cast to scala.collection.mutable.Map
  ... 63 elided

scala> Serialization.read[Map[String, Int]]("""{"a": 1, "b": 2, "c": 3}""")
res18: Map[String,Int] = Map(a -> 1, b -> 2, c -> 3)
```

**Comment by vveiler** [comment]
+1

**Comment by willyau** [comment]
+1

**Comment by liuchg5** [comment]
+1

**Comment by seratch** [comment]
Let me close this issue by merging #310.
