### ISSUE TITLE
org.json4s.package$MappingException: Can't find constructor for <case class>

### ISSUE THREAD

**Issue by lovesh** [json4s/json4s#143]
i have a outer class and then a few inner case classes like this

``` scala
class OuterClass {
implicit val formats = DefaultFormats
case class Log1(
      required: String,
      description: String
      )

  case class Log2(
      lat: Option[Double],
      lon: Option[Double],
      name: String
      )


  case class Event(
      id: String,
      name: String,
      description: String,
      time: Int,
      log1: Option[log1],
      log2: Option[log2]
      )
def getEvents() = {
     val json = HTTPRequest.getJSON(url)
     val results = json \ "results"
     val events = results.children.map {case j: JObject => j.extract[Event]}
    .......
}

}
```

The line `val events = results.children.map {case j: JObject => j.extract[Event]}` gives exception

```
org.json4s.package$MappingException: Can't find constructor for Event
        at org.json4s.reflect.ScalaSigReader$.readConstructor(ScalaSigReader.scala:27)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:108)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$6.apply(Reflector.scala:98)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$6.apply(Reflector.scala:95)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:95)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3$$anonfun$13.apply(Reflector.scala:148)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3$$anonfun$13.apply(Reflector.scala:122)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3.apply(Reflector.scala:122)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3.apply(Reflector.scala:116)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.constructorsAndCompanion(Reflector.scala:116)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:156)
        at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:50)
        at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
        at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
        at org.json4s.reflect.package$Memo.apply(package.scala:39)
        at org.json4s.reflect.Reflector$.describe(Reflector.scala:44)
        at org.json4s.Extraction$.extract(Extraction.scala:330)
        at org.json4s.Extraction$.extract(Extraction.scala:42)
        at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
        at crawler.event_sources.Meetup$$anonfun$6.apply(Meetup.scala:101)
        at crawler.event_sources.Meetup$$anonfun$6.apply(Meetup.scala:101)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
```

Any reason why `Event`'s constructor is not visible?

**Comment by zbstof** [comment]
I got similar error when I use Option[Int]:
```
import org.json4s.jackson.Serialization.writePretty
implicit val formats: org.json4s.DefaultFormats.type = org.json4s.DefaultFormats

case class TestOptionInt(table_name: Option[Int])
writePretty(TestOptionInt(Some(42)))

org.json4s.package$MappingException: Can't find constructor for TestOptionInt
  at org.json4s.reflect.ScalaSigReader$.readConstructor(ScalaSigReader.scala:27)
  at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:108)
```

But this is in spark-shell on fairly old cloudera installation `version 2.3.0.cloudera3`, works fine on latest spark `version 2.4.4`
