### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by sinban04** [json4s/json4s#1459]
### json4s version

4.0.7

### scala version

2.12.10

### jdk version

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)

## Error
- When i try to use this functions, after converting XML to Json
```scala
    val json = toJson(xml)
    pretty(render(json)
```
- It returns an error w/ message of NoSuchMethodError ... Lorg/json4s/JValue;

### Dependencies
```xml
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.json4s/json4s-native -->
    <dependency>
        <groupId>org.json4s</groupId>
        <artifactId>json4s-native_2.12</artifactId>
        <version>4.0.0</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.json4s/json4s-core -->
    <dependency>
        <groupId>org.json4s</groupId>
        <artifactId>json4s-core_2.12</artifactId>
        <version>4.0.0</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.json4s/json4s-xml -->
    <dependency>
        <groupId>org.json4s</groupId>
        <artifactId>json4s-xml_2.12</artifactId>
        <version>4.0.0</version>
    </dependency>
```

### Log
```
Caused by: java.lang.NoSuchMethodError: org.json4s.prefs.EmptyValueStrategy.replaceEmpty(Lorg/json4s/JValue;)Lorg/json4s/JValue;
        at org.json4s.native.JsonMethods.render(JsonMethods.scala:42)
        at org.json4s.native.JsonMethods.render$(JsonMethods.scala:37)
        at org.json4s.native.JsonMethods$.render(JsonMethods.scala:83)
        at com.naver.airspace.recsysops.App$.$anonfun$refineBlogData$2(App.scala:161)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
        at scala.collection.Iterator$SliceIterator.next(Iterator.scala:271)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
        at scala.collection.TraversableOnce.to(TraversableOnce.scala:315)
        at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313)
        at scala.collection.AbstractIterator.to(Iterator.scala:1429)
        at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:307)
        at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:307)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1429)
        at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:294)
        at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:288)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1429)
        at org.apache.spark.rdd.RDD.$anonfun$take$2(RDD.scala:1449)
        at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by sinban04** [comment]
It seems `render` returns not just org.json4s.native.Document, but some other type.. 
```
[ERROR] /home1/irteam/base/src/main/scala/com/naver/airspace/recsysops/App.scala:166: error: type mismatch;
[ERROR]  found   : (org.json4s.JValue, Boolean, org.json4s.prefs.EmptyValueStrategy) => org.json4s.native.Document
[ERROR]  required: org.json4s.native.Document
[ERROR]         rddRaw.take(20).foreach(println(compact(render _)))
[ERROR]                                                 ^
[ERROR] one error found
```
