### ISSUE TITLE
Extraction still fails with Scala 3 ("NoClassDefFoundError: scala/quoted/staging/package$")

### ISSUE THREAD

**Issue by Fluf22** [json4s/json4s#1520]
### json4s version
```
libraryDependencies += "org.json4s" %% "json4s-native" % "4.1.0-M7"
```

### scala version
```
ThisBuild / scalaVersion := "3.5.0"
```

### jdk version
```
$ java -version
openjdk version "22.0.2" 2024-07-16
```

### repro

```scala
import org.json4s.native.JsonParser
import org.json4s.jvalue2extractable

case class Record(id: String, value: Option[Int] = None)

object Main {
  def main(args: Array[String]): Unit = {
    implicit val formats: org.json4s.Formats = org.json4s.DefaultFormats

    val json = JsonParser.parse("""{"id":"abc"}""")
    println(json.extract[Record])
  }
}
```

### issue
```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/quoted/staging/package$
	at org.json4s.reflect.ScalaSigReader$.readConstructor(ScalaSigReader.scala:42)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:181)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$5(Reflector.scala:171)
	at scala.collection.immutable.List.map(List.scala:247)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:169)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$16(Reflector.scala:264)
	at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:75)
	at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:35)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.createConstructorDescriptors$$anonfun$3(Reflector.scala:241)
	at scala.collection.immutable.List.map(List.scala:247)
	at scala.collection.immutable.List.map(List.scala:79)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.createConstructorDescriptors(Reflector.scala:220)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.constructorsAndCompanion(Reflector.scala:199)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:296)
	at org.json4s.reflect.Reflector$.createDescriptorWithFormats(Reflector.scala:87)
	at org.json4s.reflect.Reflector$.describeWithFormats$$anonfun$1(Reflector.scala:70)
	at org.json4s.reflect.Memo.apply(Memo.scala:12)
	at org.json4s.reflect.Reflector$.describeWithFormats(Reflector.scala:70)
	at org.json4s.Extraction$.extract$$anonfun$7(Extraction.scala:456)
	at org.json4s.Extraction$.customOrElse$$anonfun$1(Extraction.scala:781)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:214)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:213)
	at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:367)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:781)
	at org.json4s.Extraction$.extract(Extraction.scala:465)
	at org.json4s.Extraction$.extract(Extraction.scala:56)
	at org.json4s.ExtractableJsonAstNode$.extract$extension(ExtractableJsonAstNode.scala:22)
	at Main$.main(Main.scala:13)
	at Main.main(Main.scala)
```

Please note that putting only strings in the class will work as intended. I had to put an Int or a Boolean for example for it to crash.
Marking the types as Optional doesn't seem to have any effect.

**Comment by xuwei-k** [comment]
please use latest Scala 3.3.4-RC version (not 3.4.x or higher) and add explicit scala3-staging dependency.
because `scala3-staging` does not guarantee binary compatibility.

**Comment by xuwei-k** [comment]
https://github.com/xuwei-k/json4s-issue-1520

**Comment by Fluf22** [comment]
Thank you @xuwei-k , it does work with your example!
