### ISSUE TITLE
IndexOutOfBoundsException when parsing a Map[String, String]

### ISSUE THREAD

**Issue by adamw** [json4s/json4s#1575]
The following code:

```scala
//> using dep org.json4s::json4s-native:4.0.7
@main def test(): Unit =
  given Serialization = org.json4s.native.Serialization
  given Formats = org.json4s.DefaultFormats

  val json = """
  {
    "headers": {
      "h1": "v1", 
      "h2": "v2"
    }
  }"""

  case class Response(headers: Map[String, String])
  org.json4s.native.Serialization.read[Response](json)
```

throws:

```
[error] org.json4s.MappingException: unknown error
[error]         at org.json4s.Extraction$.extract(Extraction.scala:60)
[error]         at org.json4s.ExtractableJsonAstNode$.extract$extension(ExtractableJsonAstNode.scala:22)
[error]         at org.json4s.native.Serialization$.read(Serialization.scala:80)
[error]         at org.json4s.Serialization.read(Serialization.scala:31)
[error]         at org.json4s.Serialization.read$(Serialization.scala:5)
[error]         at org.json4s.native.Serialization$.read(Serialization.scala:33)
[error]         at sttp.client4.examples.getAndParseJsonPekkoHttpJson4s$package$.test(getAndParseJsonPekkoHttpJson4s.scala:52)
[error]         at sttp.client4.examples.test.main(getAndParseJsonPekkoHttpJson4s.scala:39)
[error]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[error] Caused by: java.lang.IndexOutOfBoundsException: 0
[error]         at scala.collection.LinearSeqOps.apply(LinearSeq.scala:131)
[error]         at scala.collection.LinearSeqOps.apply$(LinearSeq.scala:128)
[error]         at scala.collection.immutable.List.apply(List.scala:79)
[error]         at org.json4s.Extraction$.extract$$anonfun$5(Extraction.scala:423)
[error]         at org.json4s.Extraction$.customOrElse$$anonfun$1(Extraction.scala:781)
[error]         at scala.PartialFunction.applyOrElse(PartialFunction.scala:214)
[error]         at scala.PartialFunction.applyOrElse$(PartialFunction.scala:213)
[error]         at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:367)
[error]         at org.json4s.Extraction$.customOrElse(Extraction.scala:781)
[error]         at org.json4s.Extraction$.extract(Extraction.scala:439)
[error]         at org.json4s.Extraction$ClassInstanceBuilder.buildMandatoryCtorArg(Extraction.scala:662)
[error]         at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:635)
[error]         at org.json4s.Extraction$$anon$3.applyOrElse(Extraction.scala:690)
[error]         at org.json4s.Extraction$$anon$3.applyOrElse(Extraction.scala:689)
[error]         at scala.collection.StrictOptimizedIterableOps.collect(StrictOptimizedIterableOps.scala:151)
[error]         at scala.collection.StrictOptimizedIterableOps.collect$(StrictOptimizedIterableOps.scala:136)
[error]         at scala.collection.immutable.ArraySeq.collect(ArraySeq.scala:35)
[error]         at org.json4s.Extraction$ClassInstanceBuilder.instantiate(Extraction.scala:695)
[error]         at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:768)
[error]         at org.json4s.Extraction$.extract$$anonfun$7(Extraction.scala:463)
[error]         at org.json4s.Extraction$.customOrElse$$anonfun$1(Extraction.scala:781)
[error]         at scala.PartialFunction.applyOrElse(PartialFunction.scala:214)
[error]         at scala.PartialFunction.applyOrElse$(PartialFunction.scala:213)
[error]         at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:367)
[error]         at org.json4s.Extraction$.customOrElse(Extraction.scala:781)
[error]         at org.json4s.Extraction$.extract(Extraction.scala:465)
[error]         at org.json4s.Extraction$.extract(Extraction.scala:56)
[error]         at org.json4s.ExtractableJsonAstNode$.extract$extension(ExtractableJsonAstNode.scala:22)
[error]         at org.json4s.native.Serialization$.read(Serialization.scala:80)
[error]         at org.json4s.Serialization.read(Serialization.scala:31)
[error]         at org.json4s.Serialization.read$(Serialization.scala:5)
[error]         at org.json4s.native.Serialization$.read(Serialization.scala:33)
[error]         at sttp.client4.examples.getAndParseJsonPekkoHttpJson4s$package$.test(getAndParseJsonPekkoHttpJson4s.scala:52)
[error]         at sttp.client4.examples.test.main(getAndParseJsonPekkoHttpJson4s.scala:39)
[error]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

### json4s version

4.0.7

### scala version

3.3.4

### jdk version

openjdk version "21.0.2" 2024-01-16

**Comment by xuwei-k** [comment]
https://github.com/json4s/json4s/tree/v4.1.0-M8?tab=readme-ov-file#serializing-classes-defined-in-traits-or-classes

workaround:

```diff
 //> using dep org.json4s::json4s-native:4.0.7
 
+case class Response(headers: Map[String, String])
+
 @main def test(): Unit = {
   given org.json4s.Serialization = org.json4s.native.Serialization
   given org.json4s.Formats = org.json4s.DefaultFormats
@@ -14,5 +12,6 @@ case class Response(headers: Map[String, String])
     }
   }"""
 
-  case class Response(headers: Map[String, String])
   println(org.json4s.native.Serialization.read[Response](json))
```
