### ISSUE TITLE
Json4s with play framework Actions issue

### ISSUE THREAD

**Issue by dara0418** [json4s/json4s#174]
Hi,

I have been using Json4s for a while. It's really very good. Unlike play framework's default Json lib, Json4s makes much less noise. I have an issue with using Json4s with play framework, I do know it's NOT a problem with Json4s, it should because the Play Controller/Action does some "magic" trick implicitly. But I think if I post this issue on the Play issue tracker, they will probably ignore it or kick the ball back or suggest me to use their Json lib. I also think maybe you have known this issue already so I can get faster help.

And here's my issue...

In a case class, I may need some "one-way" optional fields, which means they are optional to client side, but aren't optional to the API side. So I set some default values in the case class. For example, I have:

```
case class Account (
  id: Option[Int] = None,
  email: String,
  password: String,
  firstName: String,
  lastName: String,
  state: String = "active",
  groupID: Int,
  isGroupAdmin: Boolean = false
)
```

The "state" and "isGroupAdmin" fields are optional to client side as they have default values. Given the JSON string:

```
{
   "email":"test@gmail.com",
   "firstName":"test1",
   "lastName":"test2",
   "password":"111111",
   "groupID":1,
   "isGroupAdmin":true
}
```

The "state" is missing in the JSON string above. If I try to extract this json string to "Account" object. I think this way is correct:

```
parse("the json string above").extract[Account]
```

This piece code will work in a general class, for example, in a main class:

```
object TestMain {
  implicit val formats = DefaultFormats

  def main(args: Array[String]) {
    val str = """
    {
      "account": 
      {
         "email":"test@gmail.com",
         "firstName":"test1",
         "lastName":"test2",
         "password":"111111",
         "groupID":1,
         "isGroupAdmin":true
      }
    }
    """

    val result = (parse(str) \ "account").extract[Account]
    println(result)
  }
}
```

The code above will work as expected. But if you put this code block into a play Action, it will complain:

```
import play.api._
import play.api.mvc._

import org.json4s._
import org.json4s.jackson.{JsonMethods => json4s}
import org.json4s.jackson.JsonMethods._
import org.json4s.jackson.Serialization._

object Application extends Controller {

  implicit val formats = DefaultFormats

  def index = Action {
    val str = """
    {
      "account":
      {
        "email":"test@gmail.com",
        "firstName":"test1",
        "lastName":"test2",
        "password":"111111",
        "groupID":1,
        "isGroupAdmin":true
      }
    }
    """
    println((json4s.parse(str) \ "account").extract[Account])

    Ok("")
  }
}
```

The code above will complain this exception:
play.api.Application$$anon$1: Execution exception[[MappingException: No usable value for state
Did not find value which can be converted into java.lang.String]]
    at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.7.jar:2.3.7]
    at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.7.jar:2.3.7]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.7.jar:2.3.7]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.7.jar:2.3.7]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.1.jar:na]

**Comment by sdiwu** [comment]
Hi, I found out this problem only happened if I run the code through Play's `activator` -> `run` command, so it seems the bugs is related with the Play framework. I have posted the issue on Play's github (see referenced link above).

**Comment by sdiwu** [comment]
The OP's guess was right :), my posted issue on play's github got rejected. If anyone want to investigate, here is [the example project][1].


  [1]: https://github.com/sdiwu/play-json4s-defaultvalue-bugs

**Comment by sdiwu** [comment]
I debugged json4s code, I found out json4s code uses `Class.forName(c, true, iter.next())` to load the default parameter value at [here][1], and I checked the 3rd parameter (class loader) is `PlayDependencyClassLoader` when the code is run in play's dev mode (activator -> run). I did some googling about PlayDependencyClassLoader and it leads up to [this issue][2]. [This article][3] also gives brief information about it.

So the `Class.forName` try to load a class which is the destination type of the extract/read, however PlayDependencyClassLoader doesn't load/contain the class, thus the class load failed and resolveClass would return None.

  [1]: https://github.com/json4s/json4s/blob/3.3/core/src/main/scala/org/json4s/reflect/ScalaSigReader.scala#L195
  [2]: https://github.com/playframework/playframework/issues/822
  [3]: http://ben-tech.blogspot.be/2013/05/play-run-in-dev-mode-and.html
