### ISSUE TITLE
JsonParser hangs on very long number

### ISSUE THREAD

**Issue by mst-appear** [json4s/json4s#176]
Parsing a very long number (1 M digits) with the native parser takes an unreasonable long time. It's reasonable that you cannot parse arbitrarily long numbers in JSON, but it would be nice if you could get a ParseException rather than hanging.

It seems to get stuck in the constructor of java.math.BigDecimal:

```
        at java.math.BigInteger.<init>(BigInteger.java:405)
        at java.math.BigDecimal.<init>(BigDecimal.java:541)
        at java.math.BigDecimal.<init>(BigDecimal.java:739)
        at scala.math.BigDecimal$.exact(BigDecimal.scala:125)
        at scala.math.BigDecimal$.apply(BigDecimal.scala:283)
        at org.json4s.ParserUtil$.parseDouble(ParserUtil.scala:206)
        at org.json4s.native.JsonParser$Parser.parseValue$1(JsonParser.scala:239)
        at org.json4s.native.JsonParser$Parser.nextToken(JsonParser.scala:292)
        at org.json4s.native.JsonParser$$anonfun$1.apply(JsonParser.scala:159)
        at org.json4s.native.JsonParser$$anonfun$1.apply(JsonParser.scala:117)
        at org.json4s.native.JsonParser$.parse(JsonParser.scala:105)
        at org.json4s.native.JsonParser$.parse(JsonParser.scala:61)
        at org.json4s.native.JsonMethods$class.parse(JsonMethods.scala:13)
        at org.json4s.native.JsonMethods$.parse(JsonMethods.scala:62)
```

Perhaps a sanity check of the length of the string before trying to parse it as number? Such as not longer than 1024 characters.

**Comment by tramchamploo** [comment]
https://github.com/tramchamploo/json4s/commit/b282baa2bb75ce42aa0bc982f212e107099c839f

**Comment by seratch** [comment]
Adequate fix for this with test code is welcome.
