### ISSUE TITLE
Parsing result of rendering primitive throws an error.

### ISSUE THREAD

**Issue by folex** [json4s/json4s#226]
Maybe I just don't understand how such cases should be handled, but for me it's quite obvious that `serialize * deserialize` should be `identity`. 

```
import org.json4s.Extraction
import org.json4s.native.JsonMethods._

val serialized = compact(render(Extraction.decompose("Huh")))
val original = parse(serialized).extract[String]
```

If I'm wrong about that, sorry and thanks in advance for nice explanation ;)

**Comment by dozed** [comment]
What version are you using? `"org.json4s" %% "json4s-jackson" % "3.2.10"` works for me:

```scala
object json4s_test extends App {

  import org.json4s.Extraction
  import org.json4s.DefaultFormats
  import org.json4s.jackson.JsonMethods._

  implicit val formats = DefaultFormats

  val serialized = compact(render(Extraction.decompose("Huh")))
  val original = parse(serialized).extract[String]

  println(serialized)  // "Huh"
  println(original)     // Huh

}
```

**Comment by folex** [comment]
Sorry for long response. 
It's `3.2.11`.

**Comment by magnolia-k** [comment]
@folex Sorry for responding to a very old issue, is there any code that reproduces the problem listed in this issue?

**Comment by folex** [comment]
Hi @magnolia-k! I just tried ([scastie](https://scastie.scala-lang.org/WMfS6TEySSmFHfdiS7yaQQ)) with `3.2.11`, and I don't see any problems, it prints `Huh` in both cases. My bad on not including output :( 

I think issue can be closed. Thanks! :)

P.S. I notice absence of `DefaultFormats` in my code, maybe that was the reason.

**Comment by folex** [comment]
Oh, I managed to reproduce it with `json4s / native` `3.2.11` https://scastie.scala-lang.org/r4I2nfgBQ1ii5IGr6gSltA

```
org.json4s.ParserUtil$ParseException: expected field or array
Near: "Huh"
	at org.json4s.native.JsonParser$Parser.fail(JsonParser.scala:207)
	at org.json4s.native.JsonParser$$anonfun$1.newValue$1(JsonParser.scala:155)
	at org.json4s.native.JsonParser$$anonfun$1.apply(JsonParser.scala:164)
	at org.json4s.native.JsonParser$$anonfun$1.apply(JsonParser.scala:117)
	at org.json4s.native.JsonParser$.parse(JsonParser.scala:105)
	at org.json4s.native.JsonParser$.parse(JsonParser.scala:53)
	at org.json4s.native.JsonMethods$class.parse(JsonMethods.scala:11)
	at org.json4s.native.JsonMethods$.parse(JsonMethods.scala:62)
	at json4s_test$.delayedEndpoint$json4s_test$1(main.scala:10)
```

**Comment by magnolia-k** [comment]
@folex 
thanks!
I reproduced the problem 3.7.0-M2, too.
I will analyze it from now on.

**Comment by magnolia-k** [comment]
@folex 

The current native parser does not meet the JSON specifications since RFC 7159.
More specifically, top-level objects other than Array and Object are now allowed, but the native parser cannot handle them correctly.

The Jackson parser satisfies JSON specifications since RFC 7159, so it can be parsed correctly.

The current native parser does not meet the latest standards, so we recommend using the Jackson parser.
