### ISSUE TITLE
Problem with default fields and Apache Spark

### ISSUE THREAD

**Issue by sgomezg** [json4s/json4s#274]
Hi,

I'm having some troubles with default fields deserialization and Apache Spark. I know this is not your problem, but I hope maybe you can help me. I have a class like:

```case class Person(name:String,gender:String = "male")```

Ok. This works fine in some cases except through Apache Spark. If I package my app and I just call the method with same params, It's fails with:

```
org.json4s.package$MappingException: No usable value for persons
No usable value for gender
Did not find value which can be converted into java.lang.String
	at org.json4s.reflect.package$.fail(package.scala:96)
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:443)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:463)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:463)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$instantiate(Extraction.scala:451)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$6.apply(Extraction.scala:491)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$6.apply(Extraction.scala:488)
	at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:500)
	at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:488)
	at org.json4s.Extraction$.extract(Extraction.scala:332)
	at org.json4s.Extraction$.extract(Extraction.scala:42)
	at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
	at com.stratio.sparkta.driver.util.PolicyUtils$.parseJson(PolicyUtils.scala:41)
	at com.stratio.sparkta.driver.service.SparktaJob$.runSparktaJob(SparktaJob.scala:127)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:23)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:28)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:30)
	at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:32)
	at $iwC$$iwC$$iwC$$iwC.<init>(<console>:34)
	at $iwC$$iwC$$iwC.<init>(<console>:36)
	at $iwC$$iwC.<init>(<console>:38)
	at $iwC.<init>(<console>:40)
	at <init>(<console>:42)
	at .<init>(<console>:46)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
	at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1338)
	at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
	at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
	at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
	at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
	at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:657)
	at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:665)
	at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
	at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1059)
	at org.apache.spark.repl.Main$.main(Main.scala:31)
	at org.apache.spark.repl.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:664)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:169)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:192)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:111)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.json4s.package$MappingException: No usable value for multiplexer
Did not find value which can be converted into java.lang.String
	at org.json4s.reflect.package$.fail(package.scala:96)
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:443)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:463)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:463)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$instantiate(Extraction.scala:451)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$6.apply(Extraction.scala:491)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$6.apply(Extraction.scala:488)
	at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:500)
	at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:488)
	at org.json4s.Extraction$.extract(Extraction.scala:332)
	at org.json4s.Extraction$CollectionBuilder$$anonfun$6.apply(Extraction.scala:341)
	at org.json4s.Extraction$CollectionBuilder$$anonfun$6.apply(Extraction.scala:341)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.json4s.Extraction$CollectionBuilder.mkCollection(Extraction.scala:341)
	at org.json4s.Extraction$CollectionBuilder.result(Extraction.scala:365)
	at org.json4s.Extraction$.extract(Extraction.scala:320)
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:431)
	... 64 more
Caused by: org.json4s.package$MappingException: Did not find value which can be converted into java.lang.String
	at org.json4s.reflect.package$.fail(package.scala:96)
	at org.json4s.Extraction$.convert(Extraction.scala:554)
	at org.json4s.Extraction$.extract(Extraction.scala:331)
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:431)
	... 89 more
```

This works fine in Scala REPL and in IntelliJ. I check dependencies versions. Maybe I'm packaging wrong my app?

Did I missed something? Thanks a lot!

**Comment by seratch** [comment]
I just tried to reproduce your problem [here](https://github.com/json4s/json4s/commit/a00b9778dcdaa3345cb2dd8522ca92032caaf69f) but the same problem didn't happen. I'm afraid that your code may be wrong. For example, the `persons` doesn't exist in the type you specified to be mapped (maybe it's not the `Person` but other type which has `persons`).

**Comment by ssemichev** [comment]
I have the same problem

It works as independent project, but throw the "org.json4s.package$MappingException: No usable value for field3. Did not find value which can be converted into java.lang.String" exception in Spark application.

```
name := "json4s-test"

version := "1.0"

scalaVersion := "2.10.5"

libraryDependencies ++= Seq(
  "org.json4s" %% "json4s-jackson" % "3.2.10"
)

```
```
import org.json4s.DefaultFormats
import org.json4s.JsonDSL._


object Json4sTest extends App {

  implicit val formats = DefaultFormats

  val json = ("field1" -> "field1") ~ ("field2" -> "field2")

  val dto = json.extract[TestDto]

  assert(dto.field1 == "field1")
  assert(dto.field2 == "field2")
  assert(dto.field3 == "")
  assert(dto.field4 == null)

}

class TestDto(
    val field1: String,
    val field2: String,
    val field3: String = "",
    val field4: String = null)
```

**Comment by mguindin** [comment]
I've had this issue before.  The main problem was that the field was missing from the JSON string being deserialized/extracted.  I changed this to make that field an `Option` and the issue was resolved (along with changing everything referencing that field from the class to be `getOrElse`).  It was a bit annoying, but this has been working well in spark 1.5.2 and json4s 3.2.11

**Comment by ligadata-mjalajel** [comment]
@seratch the problem I'm facing (and I believe @sgomezg is referring to), is that json4s is throwing an exception when a value is not present although a default value is defined in the constructor. You can reproduce it by modifying the test case to be:

    "#274 Examples with default value should be parsed and default values should be filled in" in {
      val res = WithDefaultValueHolder(Seq(WithDefaultValue("Bob", "male")))
      parse("""{"values":[{"name":"Bob"}]}""").extract[WithDefaultValueHolder](
        DefaultFormats, Manifest.classType(classOf[WithDefaultValueHolder])) must_== (res)
    }

    case class WithDefaultValueHolder(values: Seq[WithDefaultValue])
    case class WithDefaultValue(name: String, gender: String = "male")


@mguindin Your solution works, but I'd like to avoid wrapping concrete values with `Option` whenever possible.

**Comment by tribbloid** [comment]
+1 affects me as well, is there a patch that is working?

**Comment by gordontyler** [comment]
I've also just encountered the same problem. I have a case class defined like so:

```scala
case class Config(
  input: Option[EventHubInputConfig]
)

case class EventHubInputConfig(
  namespace: String,
  name: String,
  partitions: Int,
  policy: String,
  key: String,
  group: String,
  checkpointURL: String,
  enqueueTime: String = "now"
)
```

And the JSON I'm trying to parse looks like this:

```json
{
  "input": {
    "namespace": "my-namespace",
    "name": "events",
    "partitions": 2,
    "policy": "Listen",
    "key": "access key",
    "group": "my-app",
    "checkpointURL": "hdfs://namenode:9000/checkpoint/events"
  }
}
```

The code which parses that JSON with that case class works in unit tests but fails when executing in Spark. The failure is _silent_, by which I mean that the `Config` object returned has the value `None` for the `input` field. If there is an exception thrown, it does not reach my code. If I add an "enqueueTime" field to the JSON, it parses correctly in Spark.

I'm using json4s 3.2.11 for compatibility with Spark. Using a newer version results in errors due to class incompatibilities.

**Comment by gordontyler** [comment]
When I alter the `enqueueTime` field definition to `enqueueTime: Option[String] = Some("now")`, parsing the example JSON in Spark results in the field being set to `None`.

**Comment by tribbloid** [comment]
Affect me as well (v3.2.10 on scala 2.10.6), only appears when submitted to Spark & use its class loader. I have full log in both cases to demonstrate the difference.

**Comment by RPCMoritz** [comment]
Ran into this also. Really disheartening to have something work in unit-testing and then fail in the cluster.
This is somewhat tricky to debug, since it only happens remotely, I suspect a serialization issue or configuration conflict behind this.

**Comment by acmitch** [comment]
We ran into this issue but worked around it by just creating a companion object and multiple apply methods for whatever we needed.

```scala
object Store extends Serializable {
  def apply(): Store =
    new Store(Utils.generateUUID)
  def apply(id: String): Store =
    new Store(id)
}

case class Store private(id: String) extends Jsonable {}
```

**Comment by akferoz** [comment]
Was this ever resolved? 
What's the best approach for more complex scala case-classes in Spark?

**Comment by tribbloid** [comment]
+1: Also affects me.

**Comment by jeffpicard** [comment]
+1: Also affects me.

**Comment by HyukjinKwon** [comment]
+1: Also affects me.

**Comment by gppeixoto** [comment]
+1, looks like this is still an unresolved (or at least with some not-so-clean-workarounds) issue.

**Comment by winty56** [comment]
+1: Also I suffered greatly from this problem. I spent two days looking for another cause.

**Comment by zzl1787** [comment]
+1: Also affects me.

**Comment by rriclet** [comment]
Same here !
We parsed a JSON and tried to extract it into a case class.

We ended up creating a JValue with default values and merging it with our parsed JSON.
Then, we use the extract method on the merged JValue.

**Comment by laiyijie** [comment]
+1: Also affects me.

**Comment by mansivirani** [comment]
+1: Also affects me. I am trying to map the case class object directly from a json string, so I wrote an apply method in the companion object of the case class that takes all parameters except the optional one, and then creates an object by providing the default value for optional field, but looks like in extract, it always goes to the default apply method which expects all properties (i.e. including optional) and hence throws a mapping exception. Any solution for this use case?

**Comment by Ashwin-Nikam** [comment]
Also affects me.

**Comment by magnolia-k** [comment]
Can anyone please provide a minimal set of code that reproduces this at this time?

I can't reproduce this issue.

**Comment by wyk-qyf** [comment]
> Can anyone please provide a minimal set of code that reproduces this at this time?
> 
> I can't reproduce this issue.

```
  case class Person(name: String, age: Int, birthday: String="")
  @Test
  def j()={
    import org.json4s.{DefaultFormats, Extraction, Formats}
    import org.json4s.jackson.JsonMethods._
    import org.json4s.jackson.JsonMethods.pretty
    import org.json4s.jackson._
    implicit val formats: Formats = DefaultFormats
    val jvalue1 = parse("""{"name" : "iteblog", "age" : 110 }""")
    val person_1 = Extraction.extract[Person](jvalue1)
    println(person_1)

```
@magnolia-k

**Comment by yosefbs** [comment]
+1: Also affects me.

>   case class Person(name: String, age: Int, birthday: String="")
  @Test
  def j()={
    import org.json4s.{DefaultFormats, Extraction, Formats}
    import org.json4s.jackson.JsonMethods._
    import org.json4s.jackson.JsonMethods.pretty
    import org.json4s.jackson._
    implicit val formats: Formats = DefaultFormats
    val jvalue1 = parse("""{"name" : "iteblog", "age" : 110 }""")
    val person_1 = Extraction.extract[Person](jvalue1)
    println(person_1)


i have the problem when use org.json4s.jackson.Serialization.read

**Comment by sathish-se** [comment]
also affects me.
