### ISSUE TITLE
custom deserializer failed for breeze.linalg.CSCMatrix at runtime

### ISSUE THREAD

**Issue by luoq** [json4s/json4s#280]
the code is below 

``` scala
import breeze.linalg._
import org.json4s._
import org.json4s.jackson.JsonMethods._
import org.json4s.jackson.Serialization
import org.json4s.jackson.Serialization.{read, write}

import scala.collection.immutable.Nil
import scala.collection.mutable.ListBuffer

/**
 * Created by lq on 8/6/15.
 */

object JsonSerializers {

  class DenseMatrixSerializer extends CustomSerializer[DenseMatrix[Double]](format => ( {
    case JObject(JField("jsonClass", JString("DenseMatrix")) :: JField("rows", JInt(rows)) :: JField("cols", JInt(cols)) :: JField("data", data_) :: Nil) => {
      val data = data_.extract[List[Double]]
      new DenseMatrix[Double](rows.toInt, cols.toInt, data.toArray)
    }
  }, {
    case m: DenseMatrix[Double] =>
      JObject(JField("jsonClass", JString("DenseMatrix")) :: JField("rows", JInt(m.rows)) :: JField("cols", JInt(m.cols)) :: JField("data", Extraction.decompose(m.data.toList)) :: Nil)
  }
    ))

  class SparseMatrixSerializer extends CustomSerializer[CSCMatrix[Double]](format => ( {
    case JObject(JField("jsonClass", JString("SparseMatrix")) :: JField("rows", JInt(rows)) :: JField("cols", JInt(cols)) ::
      JField("i", i_) :: JField("j", j_) :: JField("v", v_) :: Nil) => {
      val i = i_.extract[List[Int]]
      val j = j_.extract[List[Int]]
      val v = v_.extract[List[Double]]
      val builder = new CSCMatrix.Builder[Double](rows = rows.toInt, cols = cols.toInt)
      for ((a, (b, c)) <- i.zip(j.zip(v)))
        builder.add(a, b, c)
      builder.result()
    }
  }, {
    case m: CSCMatrix[Double] => {
      val (loc, v) = m.activeIterator.toList.unzip
      val (i, j) = loc.unzip
      JObject(JField("jsonClass", JString("SparseMatrix")) :: JField("rows", JInt(m.rows)) :: JField("cols", JInt(m.cols)) ::
        JField("i", Extraction.decompose(i)) :: JField("j", Extraction.decompose(j)) :: JField("v", Extraction.decompose(v)) :: Nil)
    }
  }
    ))

  implicit val formats = Serialization.formats(NoTypeHints) + new DenseMatrixSerializer() + new SparseMatrixSerializer()
}

object Test extends App {

  import JsonSerializers.formats

  //  val tmp = """{"jsonClass":"DenseMatrffix","rows":3,"cols":3,"data":[0.1,0.2,-0.1,0.21,0.1,-0.2,0.3,0.0,-0.3]}"""
  //  val m_new = read[DenseMatrix[Double]](tmp)

  //  val tmp ="[0.1,0.2,-0.1,0.21,0.1,-0.2,0.3,0.0,-0.3]"
  //  val x = read[Array[Double]](tmp)
  //  println(x)

  val m2Builder = new CSCMatrix.Builder[Double](100, 100)
  m2Builder.add(1, 32, 1.2)
  m2Builder.add(13, 13, 12.3)
  m2Builder.add(11, 32, -12)
  val m2 = m2Builder.result()
  val ser2 = write(m2)
  val m2_new = parse(ser2).extract[CSCMatrix[Double]]
  //  m2_new shouldEqual m2
}
```

The exception is below

```
org.json4s.package$MappingException: Can't find constructor for CSCMatrix[double]
        at org.json4s.reflect.ScalaSigReader$.readConstructor(ScalaSigReader.scala:27)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:108)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3$$anonfun$13.apply(Reflector.scala:148)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3$$anonfun$13.apply(Reflector.scala:122)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3.apply(Reflector.scala:122)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3.apply(Reflector.scala:116)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.constructorsAndCompanion(Reflector.scala:116)
        at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:156)
        at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:50)
        at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
        at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
        at org.json4s.reflect.package$Memo.apply(package.scala:39)
        at org.json4s.reflect.Reflector$.describe(Reflector.scala:44)
        at org.json4s.Extraction$.extract(Extraction.scala:330)
        at org.json4s.Extraction$.extract(Extraction.scala:42)
        at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
        at com.datayes.gaea.whale.algorithm.industry.classification.models.PlayGround$delayedInit$body.apply(PlayGround.scala:28)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
        at scala.App$class.main(App.scala:71)
        at com.datayes.gaea.whale.algorithm.industry.classification.models.PlayGround$.main(PlayGround.scala:11)
        at com.datayes.gaea.whale.algorithm.industry.classification.models.PlayGround.main(PlayGround.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by luoq** [comment]
The error occurs at last line; It's ok for DenseMatrix[Double].

DenseMatrix, CSCMatrix are defined at:

https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/linalg/DenseMatrix.scala
https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/linalg/CSCMatrix.scala

**Comment by magnolia-k** [comment]
@luoq 

Is this question still valid?

The presented code could not be compiled as is.
By changing the definition of formats, I was able to compile and execute. (The version of Json4s used 3.6.7)

Could you close the issue if it was resolved?
