### ISSUE TITLE
DefaultFormats shows error : java.lang.AbstractMethodError 

### ISSUE THREAD

**Issue by msimar** [json4s/json4s#317]
Environment: 
Scala : 2.10.6
libraryDependencies += "org.json4s" % "json4s-native_2.10" % "3.3.0" 
libraryDependencies += "org.json4s" % "json4s-ast_2.10" % "3.3.0"

I am try to convert json to scala object or vice-versa. 

implicit val formats = new org.json4s.DefaultFormats { 
       override def dateFormatter: java.text.SimpleDateFormat =  new java.text.SimpleDateFormat("yyyy/MM/dd HH:mm:ss")
 }

extending DefaultFormats leads to following error.

java.lang.AbstractMethodError: fi.helsinki.cs.TimeSeries$$anon$1.org$json4s$DefaultFormats$_setter_$strict_$eq(Z)V
at org.json4s.DefaultFormats$class.$init$(Formats.scala:326)

**Comment by rafaelbarreto87** [comment]
+1 I'm having the exact same problem.

**Comment by shezarkhani** [comment]
:+1: me too

**Comment by ljmachado** [comment]
+1

**Comment by dzolnai** [comment]
As a workaround, you can use version 3.2.11, which doesn't seem to have this issue.

**Comment by pbamba** [comment]
Any update on that ?

**Comment by seratch** [comment]
I'm afraid that the issue happens when mixing json4s 3.2.x and 3.3.x somehow. Please ensure the libraryDependencies. sbt-dependency-graph should be useful for the investigation.

**Comment by tribbloid** [comment]
+1
BTW: @seratch this is not caused by mixing minor version
My dependencies only differs in patch versions: 3.2.11 vs 3.2.10 and it also get the same error.

**Comment by sammylee-optimizely** [comment]
Any solutions to this as I just encountered this error as well...

**Comment by seratch** [comment]
@tribbloid We had a binary-compatibility issue between 3.2.10 and 3.2.11. The problem affected many users. https://github.com/json4s/json4s/issues/212

Not to repeat the situation, we have been guaranteeing bin-compatibilities among patch versions since 3.3 series.

**Comment by zkid18** [comment]
@seratch 
I've encountered the same error. 

```
object JsonLoader {
 def parseJsonConfig[T: Manifest](filename: String): T = {
  implicit lazy val formats: DefaultFormats = new DefaultFormats {
     override val strictOptionParsing: Boolean = true
    }

  val inputStream = getClass.getResourceAsStream(filename)
  val lines = try {
   Source.fromInputStream(new BufferedInputStream(inputStream)).getLines.mkString
  } catch {
   case _: Exception => throw new Exception("config file not found")
  }
  parse(lines, useBigDecimalForDouble = false).extract[T]
 }
}
```

I'm on 3.5.0 version
```
Exception in thread "main" java.lang.AbstractMethodError
 at org.json4s.DefaultFormats$class.$init$(Formats.scala:329)
 at jp.co.yahoo.k2.i2i.optimizer.util.JsonLoader$$anon$1.<init>(JsonLoader.scala:16)
 at jp.co.yahoo.k2.i2i.optimizer.util.JsonLoader$.parseJsonConfig(JsonLoader.scala:16)
```

Any thoughts?

**Comment by zkid18** [comment]
As it was mentioned above the compatibility issue caused this problem.

**Comment by zkid18** [comment]
Should we close that issue?
