### ISSUE TITLE
json4s-jackson 3.3.0 doesn't work in a Spark 1.5.1 application (Scala 2.11.7)

### ISSUE THREAD

**Issue by manuelkiessling** [json4s/json4s#320]
I've written a small Spark application (see https://github.com/journeymonitor/analyze/blob/master/spark/src/main/scala/SparkApp.scala) which compiles against Scala 2.11.7 and runs within Spark 1.5.1. I'm using Oracle JDK 1.7.0_79-b15 on Mac OS X 10.11.1.

I was previously using json4s-native 3.3.0 without problems, but when switching to json4s-jackson 3.3.0, my tests fail with:

    java.lang.VerifyError:
    class com.fasterxml.jackson.module.scala.ser.ScalaIteratorSerializer overrides
    final method withResolved.(
        Lcom/fasterxml/jackson/databind/BeanProperty;
        Lcom/fasterxml/jackson/databind/jsontype/TypeSerializer;
        Lcom/fasterxml/jackson/databind/JsonSerializer;)
        Lcom/fasterxml/jackson/databind/ser/std/AsArraySerializerBase;
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)

Switching to json4s-jackson 3.2.10 solves this problem.

**Comment by xuwei-k** [comment]
https://github.com/json4s/json4s/issues/316

**Comment by manuelkiessling** [comment]
Thanks. I searched the issues for "Spark", but forgot to include closed issues in the search scope.
