### ISSUE TITLE
Type alias for parameterized type in case class causes `java.lang.IndexOutOfBoundsException`

### ISSUE THREAD

**Issue by metasim** [json4s/json4s#336]
Test case:

```
type Foo = Seq[Int]
case class Thing(f: Foo)

Extraction.decompose(Thing(Seq(1,2,3)))
```

Exception:

```
	at org.json4s.reflect.ScalaSigReader$.findArgTypeForField(ScalaSigReader.scala:142)
	at org.json4s.reflect.ScalaSigReader$.readField(ScalaSigReader.scala:47)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:62)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:61)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.fields(Reflector.scala:61)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.properties(Reflector.scala:78)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:180)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:46)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:40)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:40)
	at org.json4s.reflect.package$Memo.apply(package.scala:36)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:40)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:122)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:68)
	at org.json4s.Extraction$.decompose(Extraction.scala:246)

```

**Comment by lminer** [comment]
I'm getting this too.

**Comment by kosii** [comment]
any update on this?

**Comment by Nekdo** [comment]
I'm getting this too.
