### ISSUE TITLE
ParseUtil NullPointerException

### ISSUE THREAD

**Issue by garyfeltham** [json4s/json4s#358]
Received the following stack trace

```
java.lang.NullPointerException
    at org.json4s.ParserUtil$.quote(ParserUtil.scala:26)
    at org.json4s.ParserUtil$.quote(ParserUtil.scala:23)
    at org.json4s.FieldStreamingJsonWriter.addAndQuoteNode(json_writers.scala:328)
    at org.json4s.StreamingJsonWriter.string(json_writers.scala:500)
    at org.json4s.StreamingJsonWriter.addJValue(json_writers.scala:528)
    at org.json4s.StreamingJsonWriter.addJValue(json_writers.scala:541)
    at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:150)
    at org.json4s.Extraction$.addField$1(Extraction.scala:114)
    at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:142)
    at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
    at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:193)
    at org.json4s.Extraction$.addField$1(Extraction.scala:114)
    at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:142)
    at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
    at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:193)
    at org.json4s.Extraction$.addField$1(Extraction.scala:114)
    at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:142)
    at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
    at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:193)
    at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:68)
    at org.json4s.native.Serialization$.write(Serialization.scala:43)
    at org.json4s.native.Serialization$.write(Serialization.scala:37)
```

The cause was due to a CustomSerializer which set the following 

```
case s:LinkedRecord[_] =>
    ("id" -> LinkedRecordFactory.encodePK(s)) ~
    ("scope" -> s.linkedTable) ~
    ("desc" -> s.desc)
```

where the data from s.desc was in fact null (caused by MySql result sets).

org.json4s.StreamingJsonWriter.addJValue(json_writers.scala:528) saw the value as JString(null) rather than JNull, presumably based on the custom serialisation process.

A potential fix is to add a null check
    case JNull => addNode("null")
    case JString(str) if str == null => addNode("null")
    case JString(str) => string(str)

I have worked around this within the custom serializer as `("desc" -> Option(s.desc))`

**Comment by garyfeltham** [comment]
note that this was fixed in https://github.com/json4s/json4s/pull/343
