### ISSUE TITLE
Can not serialize java class if it has java.util.Map

### ISSUE THREAD

**Issue by liangqing** [json4s/json4s#392]
I have a java class
```java
public class JavaClass {

    private final int value;

    private final Map<String, Object> map;

    public JavaClass(final int value) {
        this.value = value;
        map = new HashMap<>(1, 1);
        map.put("1", "3");
    }

}
```

when i serialize it by:
```scala
    implicit val formats = org.json4s.DefaultFormats
    org.json4s.jackson.Serialization.write(new JavaClass(1))
```

error happens:
```
Exception in thread "main" org.json4s.package$MappingException: Can't find ScalaSig for class test.JavaClass
	at org.json4s.reflect.ScalaSigReader$.findClass(ScalaSigReader.scala:51)
	at org.json4s.reflect.ScalaSigReader$.org$json4s$reflect$ScalaSigReader$$read$1(ScalaSigReader.scala:45)
	at org.json4s.reflect.ScalaSigReader$.readField(ScalaSigReader.scala:47)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:62)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:61)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.fields(Reflector.scala:61)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.properties(Reflector.scala:78)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:180)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:46)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:40)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:40)
	at org.json4s.reflect.package$Memo.apply(package.scala:36)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:40)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:122)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:68)
	at org.json4s.Extraction$.decompose(Extraction.scala:246)
	at org.json4s.jackson.Serialization$.write(Serialization.scala:24)
	at test.TestJsonSerializer$.delayedEndpoint$test$TestJsonSerializer$1(TestJsonSerializer.scala:178)
	at test.TestJsonSerializer$delayedInit$body.apply(TestJsonSerializer.scala:18)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
```

anything idea?

**Comment by GregYeo** [comment]
I am having a same trouble.

In my case, GraphQL library produces LinkedHashMap and it could not be decomposed by `Extraction.decompose($MapObject)`

It's a json4s problem because jackson library is supporting this Map like `new ObjectMapper().writeValueAsString($MapObject)`

It seems like the Extraction of json4s ignores java.util.Map

**Comment by tukushan** [comment]
json4s (at least v3.4.1) converts a java.util.Map into an empty JObject.

To work-around this, drop down to Jackson to create a JsonNode, and then convert it  back to a JValue:

`fromJsonNode(mapper.valueToTree(map))`

**Comment by pdemro** [comment]
I know its an old post but you saved me @tekumara thank you!
