### ISSUE TITLE
Can not serialize case class with context bound

### ISSUE THREAD

**Issue by liangqing** [json4s/json4s#394]
errors happens when i running these code:

```scala
    case class Value[T: Numeric](
        v: T
    )
    val value = Value(1000)
    implicit val formats = org.json4s.DefaultFormats
    println(org.json4s.jackson.Serialization.write(value)) //exception throws
```

```
Exception in thread "main" org.json4s.package$MappingException: Can't find constructor for Value
	at org.json4s.reflect.ScalaSigReader$.readConstructor(ScalaSigReader.scala:21)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:86)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$createConstructorDescriptors$3$$anonfun$15.apply(Reflector.scala:150)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$createConstructorDescriptors$3$$anonfun$15.apply(Reflector.scala:135)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$createConstructorDescriptors$3.apply(Reflector.scala:135)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$createConstructorDescriptors$3.apply(Reflector.scala:129)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.createConstructorDescriptors(Reflector.scala:129)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.constructorsAndCompanion(Reflector.scala:114)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:178)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:46)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:40)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:40)
	at org.json4s.reflect.package$Memo.apply(package.scala:36)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:40)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:122)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:232)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:68)
	at org.json4s.Extraction$.decompose(Extraction.scala:246)
	at org.json4s.jackson.Serialization$.write(Serialization.scala:24)
	at test.json.TestJsonSerializer$.delayedEndpoint$test$json$TestJsonSerializer$1(TestJsonSerializer.scala:204)
	at test.json.TestJsonSerializer$delayedInit$body.apply(TestJsonSerializer.scala:22)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
```

but if i remove the context bound, it works fine:
```scala
    case class Value[T](
        v: T
    )
    val value = Value(1000)
    implicit val formats = org.json4s.DefaultFormats
    println(org.json4s.jackson.Serialization.write(value)) // works fine
```

**Comment by liangqing** [comment]
I inspect the code to ScalaSigReader.scala, and make a break point to last line of this function:
```scala
  def findConstructor(c: ClassSymbol, argNames: List[String]): Option[MethodSymbol] = {
    val ms = c.children collect {
      case m: MethodSymbol if m.name == "<init>" => m
    }
    ms.find(m => m.children.map(_.name) == argNames) // break point
  }
```
I find that it maybe a order mistake
when program run at the break point, argNames is a List of List("v", "evidence$1")
ms has only one element, and the element's children attribute has two elements, first element is "evidence$1", second is "v"
This situation makes the findConstructor function return a None object, and cause the Exception
