### ISSUE TITLE
Bug: Extraction's reflection breaks on type aliases (loops endlessly or throws)

### ISSUE THREAD

**Issue by dsbos** [json4s/json4s#397]
Json4s extraction breaks on a field of a generic type whose type parameter is an alias to an `AnyVal` type (e.g., `List[X]`, where `X` is declared as "`type X = Long`").  A test case is below.

For versions before 3.4.0, Json4s code hangs in an infinite loop (infinite recursion transformed by Scala's tail-recursion optimization into endless looping).

For version 3.4.0, Json4s no longer hangs, but it still fails, throwing an exception such as:

    org.json4s.package$MappingException: Unexpected type info TypeRefType(SingleType(ThisType(ClassSymbol(Json4sAliasBugTest, owner=com.us.dsb.explore.bugs, flags=0, info=13 ,None)),ObjectSymbol(SomeObject, owner=0, flags=400, info=40 )),AliasSymbol(Alias1, owner=42, flags=0, info=55 ),List())

The loop or exception occurs in method `org.json4s.reflectScalaSigReader.findArgTypeForField(..).findPrimitive(...)`.  However, the actual problem may be elsewhere.

(The behavior seems to be the same for both Scala 2.10 and 2.11 versions of Json4s.)

I suspect that the problem is that one bit of code that checks whether the net type of a given type name is a primitive type does correctly resolve aliases, but other code forgets that a primitive type might not be specified directly with `Int`, `Long`, etc., but might be specified via an alias.)

Here's a ScalaTest test class for the bug:

    import org.json4s.DefaultFormats
    import org.json4s.Extraction.decompose
    import org.scalatest.FunSuite
    
    
    class Json4sAliasBugTest extends FunSuite {
    
      implicit val fmts = DefaultFormats
    
      object SomeObject {
        type Alias1 = Long
      }
      type Alias2 = Long
    
      class C1(val f: List[SomeObject.Alias1])
      class C2(val f: List[Alias2])
    
      test("Bug case: expect endless loop or 'MappingException: Unexpected type" +
           " info TypeRefType...' (for <3.4.0 or 3.4.0, respectively).") {
        val j = decompose(new C1(List()))
      }
    
      test("A working case.") {
        val j = decompose(new C2(List()))
      }
    }

Notes:

I also tried with the alias defined in different places (e.g., in a top-level object rather than a nested object, in a different class, etc.) and all those tries (other than the one in the second test case above) also hit the failure.

Using a type such as `Option[SomeAlias]` fails similarly.

Here is a full stack trace from running the above test:

```
Unexpected type info TypeRefType(SingleType(ThisType(ClassSymbol(Json4sAliasBugTest, owner=com.us.dsb.explore.bugs, flags=0, info=13 ,None)),ObjectSymbol(SomeObject, owner=0, flags=400, info=40 )),AliasSymbol(Alias1, owner=42, flags=0, info=55 ),List())
org.json4s.package$MappingException: Unexpected type info TypeRefType(SingleType(ThisType(ClassSymbol(Json4sAliasBugTest, owner=com.us.dsb.explore.bugs, flags=0, info=13 ,None)),ObjectSymbol(SomeObject, owner=0, flags=400, info=40 )),AliasSymbol(Alias1, owner=42, flags=0, info=55 ),List())
	at org.json4s.reflect.package$.fail(package.scala:93)
	at org.json4s.reflect.ScalaSigReader$.findPrimitive$3(ScalaSigReader.scala:147)
	at org.json4s.reflect.ScalaSigReader$.findArgTypeForField(ScalaSigReader.scala:141)
	at org.json4s.reflect.ScalaSigReader$.readField(ScalaSigReader.scala:47)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:61)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:60)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.fields(Reflector.scala:60)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.properties(Reflector.scala:77)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:178)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:45)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:40)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:40)
	at org.json4s.reflect.package$Memo.apply(package.scala:36)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:40)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:118)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:64)
	at org.json4s.Extraction$.decompose(Extraction.scala:242)
	at com.us.dsb.explore.bugs.Json4sAliasBugTest$$anonfun$1.apply$mcV$sp(Json4sAliasBugTest.scala:22)
	at com.us.dsb.explore.bugs.Json4sAliasBugTest$$anonfun$1.apply(Json4sAliasBugTest.scala:21)
	at com.us.dsb.explore.bugs.Json4sAliasBugTest$$anonfun$1.apply(Json4sAliasBugTest.scala:21)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
	at org.scalatest.FunSuite.run(FunSuite.scala:1555)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by dsbos** [comment]
This seems related to (or partly same as) #55, #76, #169, #273, #281, #324, #325.

(Note:  The multiple bug reports about this problem indicate that people are indeed trying to use type aliases (e.g., to better represent semantics of data), so please don't neglect types specified using type aliases.)

**Comment by dsbos** [comment]
#397 seems related.

**Comment by AndreiMushinsky** [comment]
I suppose the problem with this [pattern matching](https://github.com/json4s/json4s/blob/3.5/core/src/main/scala/org/json4s/reflect/ScalaSigReader.scala#L146). I've tried to replace it with `case TypeRefType(_, symbol, _) => symbol`, and it's worked. But I have no idea why this case requires the first argument of TypeRefType to be of type ThisType.

**Comment by suminb** [comment]
I'd like to try what @AndreiMushinsky suggested, so I cloned this project and built it with `sbt` as follows:

    sbt package
 
It seems to produce multiple `.jar` files but I have no idea which ones are necessary and which ones are not. I had the following line in my `build.sbt` file:

     "org.json4s" %% "json4s-jackson" % "3.5.0",

Then I commented out this line and imported the generated `.jar` files in my project. When I rebuild my project, I get the following stack trace:

    Exception in thread "main" java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
        at org.json4s.NoTypeHints$.<init>(Formats.scala:297)
        at org.json4s.NoTypeHints$.<clinit>(Formats.scala)
        (...)

This is probably a rookie question as I'm pretty much new to Scala, but any help would be much appreciated.

**Comment by AndreiMushinsky** [comment]
https://github.com/json4s/json4s/issues/397#issuecomment-265997157 Make sure that your project and json4s you've built have the same scala version. Current branch (3.6.0) is compiled against [2.12.1](https://github.com/json4s/json4s/blob/3.6/project/build.scala#L56l).

**Comment by manuzhang** [comment]
Any updates on this issue ?

**Comment by tuxslayer** [comment]
Bump :( 
Fails even for simple things like 
`type UserId = Long`

**Comment by plokhotnyuk** [comment]
@tuxslayer Hi, Alexey!
As W/A you can try [jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala). 
It supports [any type aliases](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-macros/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala) for derivation of codecs.
Also, it is much [safer](https://github.com/json4s/json4s/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+denial) and [efficient](https://plokhotnyuk.github.io/jsoniter-scala/).

**Comment by meirmaor** [comment]
What would it take to get this one fixed? Would paying or offering a bounty help? I would like to solicit proposals for fixing this. meir [at my work email] sparkbeyond com
