### ISSUE TITLE
org.json4s.package$MappingException: Do not know how to convert JString(480) into int

### ISSUE THREAD

**Issue by ghazel** [json4s/json4s#427]
The json4s extractor code manages to handle `JString("480").extract[Int]` just fine, but using a Java type inferred by my code, it fails:

```scala
foo.extract[T]
```

```
Caused by: org.json4s.package$MappingException: Do not know how to convert JString(480) into int
	at org.json4s.Extraction$.convert(Extraction.scala:608)
	at org.json4s.Extraction$.extract(Extraction.scala:350)
	at org.json4s.Extraction$.extract(Extraction.scala:42)
	at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
```

**Comment by ghazel** [comment]
Oh, it seems json4s doesn't attempt to convert json strings into ints at all.
