### ISSUE TITLE
Polymorphic Extraction is broken

### ISSUE THREAD

**Issue by farmdawgnation** [json4s/json4s#431]
### json4s version

3.5.0

### scala version

2.11.8

### jdk version

8

### Description

Polymorphic extraction of types appears to be broken whereas it works in the upstream lift-json. As an example take the following:

```scala
trait Transportation
case class Car(kind: String) extends Transportation
```

Given those types the following REPL session produces an error when you attempt to extract the Car as a `Transportation` type:

```scala
scala> val myCar = Car("Honda Accord")
myCar: Car = Car(Honda Accord)

scala> decompose(myCar)
res0: org.json4s.JValue = JObject(List((jsonClass,JString(Car)), (kind,JString(Honda Accord))))

scala> res0.extract[Transportation]
org.json4s.package$MappingException: No constructor for type Transportation, JObject(List((jsonClass,JString(Car)), (kind,JString(Honda Accord))))
  at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$constructor(Extraction.scala:470)
  at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$instantiate(Extraction.scala:525)
  at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$8.apply(Extraction.scala:590)
  at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$8.apply(Extraction.scala:585)
  at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:599)
  at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:585)
  at org.json4s.Extraction$.extract(Extraction.scala:394)
  at org.json4s.Extraction$.extract(Extraction.scala:39)
  at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
  ... 42 elided
```

This seems to work fine, on the other hand, using lift-json.

**Comment by xuwei-k** [comment]
> it works in the upstream lift-json

Do you mean `"net.liftweb" % "lift-json_2.11"` ? if so, which version?

**Comment by farmdawgnation** [comment]
In the latest. And actually for quite a long time before that.... I've depended on this behavior in applications dating back to me using Lift 2.4.

I did note that our ExtractionExamplesSpec lacks a spec demonstrating this behavior. This is a problem I'm going to be rectifying that this afternoon.

**Comment by rcoh** [comment]
Any update on this?

**Comment by farmdawgnation** [comment]
No update that I’m aware of, though if you depend on / require this behavior I would consider switching to lift-json. The rewrite of extraction between Lift-json and json4s seemed pretty extensive to me if memory serves me correctly.

We’ve formalized a six month release cycle so if the old, long cycle was your primary motivation for using json4s we have rectified that.  I still need to add a spec to our extractor and it would probably be a good idea for us to ship some json4s AST interop code too.

**Comment by stanpalatnik** [comment]
+1

**Comment by farmdawgnation** [comment]
A path forward here may be to consider pulling in a variation of the new extractor we're targeting for Lift 4: https://github.com/liftmodules/json-extractor-ng.

It's still very much a work in progress, but it's based on Scala reflection APIs and would allow us to re-unify our handling of Extraction between these two libraries. I'm aiming to get it to the point of surpassing the current Lift extractor in functionality soon, but having other folks taking it out for a walk is going to be the single most helpful thing from our point of view.

**Comment by jeannei** [comment]
👋 Is there any update on this?
