### ISSUE TITLE
Inconsistent behavior when extracting a Collection from JNothing

### ISSUE THREAD

**Issue by morgen-peschke** [json4s/json4s#456]
### json4s version
3.4.0
### scala version
2.11.8
### jdk version
1.8.0_121

I ran into this issue when deserializing a case class from an object with optional keys.

```scala
scala> JNothing.extract[List[Int]]
res0: List[Int] = List()

scala> JNothing.extract[List[(Int, Int)]]
res0: List[(Int, Int)] = List()

scala> JNothing.extract[Map[String,String]]
org.json4s.package$MappingException: Expected object but got JNothing
  at org.json4s.Extraction$.extract(Extraction.scala:374)
  at org.json4s.Extraction$.extract(Extraction.scala:39)
  at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
  ... 42 elided
```

I would have expected the `JNothing` to extract any collection to an empty collection, as it does for `List`.

**Comment by morgen-peschke** [comment]
Appears to be a duplicate of #198

**Comment by magnolia-k** [comment]
This issue has been resolved and is now closed
