### ISSUE TITLE
Deserializing "{}" to JObject with Jackson creates JObject(obj=null) which NPEs on comparison

### ISSUE THREAD

**Issue by thezerobit** [json4s/json4s#458]
### json4s version
3.5.0
### scala version
2.12.1
### jdk version
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

To reproduce:
```
    val mapper = new ObjectMapper()
    val jobject = mapper.readValue("{}", classOf[JObject])
    assert(jobject == JObject()) // java.lang.NullPointerException
```

The value created is `JObject(obj=null)` and the `equals` implementation of JObject calls `obj.toSet` which causes an NPE because `obj` is `null`. Adding the Jackson Scala support module `mapper.registerModule(DefaultScalaModule)` does not help.

**Comment by Khalian** [comment]
I think your analysis is incomplete. 

I wrote a test case for this inside json4s and got the following exception. 

<error message="Cannot construct instance of `org.json4s.JsonAST$JObject` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator) at [Source: (String)&quot;{}&quot;; line: 1, column: 2]" 
 type="com.fasterxml.jackson.databind.exc.InvalidDefinitionException">com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.json4s.JsonAST$JObject` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)&quot;{}&quot;; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1438)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1027)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1275)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:325)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at org.json4s.JsonAstSpec$.$anonfun$new$120(JsonAstSpec.scala:156)

The test case is as follows:-

    "JObject must correctly process empty value" in {
        val mapper = new ObjectMapper()
        val jobject = mapper.readValue("{}", classOf[JObject])
        jobject must_== null
    }

This is actually expected. JObject is a case class and Jackson mapping needs a default constructor with getters and setters. In order to extend a direct json port, you need to have @ JsonProperty annotated to every field https://stackoverflow.com/questions/28270621/using-jackson-to-de-serialize-a-scala-case-class, which I do not think is the correct thing to do.

**Comment by Khalian** [comment]
I ran this test case as well. It turns out this works fine. I believe you should use the parse method directly instead of using Jackson mapper. 

"Empty Json is parsed to JObject" in {
     val parseval = parse("{}")
      parseval must_== JObject()
}

**Comment by Khalian** [comment]
@seratch I think you can close this issue. Also https://github.com/json4s/json4s/pull/474 as a sanity test to corroborate my claim.

**Comment by thezerobit** [comment]
I forgot to mention that non-empty JSON objects deserialize into valid JObject instances. Other json4s types work correctly, too. As far as I could tell from my testing, everything works using the jackson ObjectMapper with the sole exception of objects with no properties ("{}"). There is no need for @ JsonProperty annotations.

Using JObject inside an existing Jackson-based workflow does not really allow for using a different parse method for a particular object type, especially when that is a property of another object being deserialized via Jackson.
