### ISSUE TITLE
android project can't use json4s library

### ISSUE THREAD

**Issue by wooi** [json4s/json4s#467]
### json4s version
3.5.2
### scala version
2.11.9
### jdk version
1.8.0_25

I'm add the json4s configure in build.sbt
```
libraryDependencies += "org.json4s" %% "json4s-jackson" % "3.5.2"
```
i'm build other sbt project without sbt-android for test this library and build successful,but in my sbt-android project compiler throw proguard error
```
java.io.IOException: Please correct the above warnings first.
	at proguard.Initializer.execute(Initializer.java:473)
	at proguard.ProGuard.initialize(ProGuard.java:233)
	at proguard.ProGuard.execute(ProGuard.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at android.Proguard$.runProguard(proguard.scala:210)
	at android.Proguard$.proguard(proguard.scala:164)
	at android.Tasks$$anonfun$86.apply(tasks.scala:1062)
	at android.Tasks$$anonfun$86.apply(tasks.scala:1060)
	at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:35)
	at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
I can't find the json4s proguard in search engine, how can I fix this issue?

**Comment by wooi** [comment]
I have solved this problem finally. I thing that it's the proguard cause this issue. The IOException was fixed after I add the proguard rule like this.

  "-dontobfuscate" ::
  "-dontoptimize" ::
  "-keepattributes Signature" ::
  "-dontwarn scala.collection.**" :: // required from Scala 2.11.3
  "-dontwarn scala.collection.mutable.**" :: // required from Scala 2.11.0
  "-ignorewarnings" ::
  "-keep class scala.Dynamic" ::
  "-keep class test.**" ::
But the next problem was come up And I add packagingOptions rule to fix duplicate of jackson.jar .

     "decoder.properties" ::
    "META-INF/LICENSE" ::
    "META-INF/LICENSE.txt" ::
    "META-INF/NOTICE" ::
    "META-INF/NOTICE.txt" ::
    "rootdoc.txt" ::
I hope this would help someone who want to use json4s lib in their android project :)
