### ISSUE TITLE
Double.{PositiveInfinity,NegativeInfinity,Nan} serializes but does not deserialize with json4s native

### ISSUE THREAD

**Issue by TronPaul** [json4s/json4s#482]
### json4s version
3.5.3
### scala version
Scala 2.11.8
### jdk version
Java 1.8.0_144

    scala> import org.json4s._; import org.json4s.native.JsonMethods._; import org.json4s.Extraction; import org.json4s.JsonDSL._; implicit val fmts = org.json4s.DefaultFormats
    import org.json4s._
    import org.json4s.native.JsonMethods._
    import org.json4s.Extraction
    import org.json4s.JsonDSL._
    fmts: org.json4s.DefaultFormats.type = org.json4s.DefaultFormats$@3eb6c489

    scala> compact(render(Map("test" -> Double.PositiveInfinity)))
    res0: String = {"test":Infinity}

    scala> parse(res0)
    org.json4s.ParserUtil$ParseException: unknown token I
    Near: {"test":I
      at org.json4s.native.JsonParser$Parser.fail(JsonParser.scala:234)
      at org.json4s.native.JsonParser$Parser.nextToken(JsonParser.scala:322)
      at org.json4s.native.JsonParser$$anonfun$1.apply(JsonParser.scala:185)
      at org.json4s.native.JsonParser$$anonfun$1.apply(JsonParser.scala:143)
      at org.json4s.native.JsonParser$.parse(JsonParser.scala:131)
      at org.json4s.native.JsonParser$.parse(JsonParser.scala:71)
      at org.json4s.native.JsonMethods$class.parse(JsonMethods.scala:10)
      at org.json4s.native.JsonMethods$.parse(JsonMethods.scala:63)
      ... 42 elided

This seems to be similar to #246, however that ticket mentions #159 fixed this issue for Infinity.

**Comment by TronPaul** [comment]
Upon further investigation it seems if a `NaN` value is a `java.lang.Double` it produces `null`. It still produces `Infinity` for `Double.PositiveInfinity` wrapped in a `java.lang.Double`.

```
scala> import org.json4s._; import org.json4s.native.JsonMethods._; import org.json4s.Extraction; import org.json4s.JsonDSL._; implicit val fmts = org.json4s.DefaultFormats                      [6/1908]
import org.json4s._
import org.json4s.native.JsonMethods._
import org.json4s.Extraction
import org.json4s.JsonDSL._
fmts: org.json4s.DefaultFormats.type = org.json4s.DefaultFormats$@daec0e6

scala> compact(render(Extraction.decompose(Map("test" -> new java.lang.Double(Double.NaN)))))
res0: String = {"test":null}

scala> parse(res0)
res1: org.json4s.JValue = JObject(List((test,JNull)))

scala> compact(render(Extraction.decompose(Map("test" -> new java.lang.Double(Double.PositiveInfinity)))))
res2: String = {"test":Infinity}

scala> parse(res2)
org.json4s.ParserUtil$ParseException: unknown token I
Near: {"test":I
  at org.json4s.native.JsonParser$Parser.fail(JsonParser.scala:234)
  at org.json4s.native.JsonParser$Parser.nextToken(JsonParser.scala:322)
  at org.json4s.native.JsonParser$$anonfun$1.apply(JsonParser.scala:185)
  at org.json4s.native.JsonParser$$anonfun$1.apply(JsonParser.scala:143)
  at org.json4s.native.JsonParser$.parse(JsonParser.scala:131)
  at org.json4s.native.JsonParser$.parse(JsonParser.scala:71)
  at org.json4s.native.JsonMethods$class.parse(JsonMethods.scala:10)
  at org.json4s.native.JsonMethods$.parse(JsonMethods.scala:63)
  ... 42 elided
```
