### ISSUE TITLE
Do not know how to serialize key of type class com.mypackage.Myclass. Consider implementing a CustomKeySerializer

### ISSUE THREAD

**Issue by welcomemandeep** [json4s/json4s#494]
### json4s version
3.6.0-M1
### scala version
2.12.3
### jdk version
1.8.0_144
I  wanted to serialize something like 
````val someMap : Map[BaseTrait, JValue] = someList.map {
    p => {
      Myclass("someParam") -> p.x
    }
  }.toMap ````

Now, case class Myclass extends BaseTrait.
I implemented a serializer for Myclass  - MyclassSerializer and added the same in the formats - 
````implicit val formats = Serialization.formats(ShortTypeHints(List(classOf[Myclass]))) + MyclassSerializer````

MyclassSerializer - 
````object MyclassSerializer extends CustomSerializer[BaseTrait](format => ( {
  // Impl
}
))
```` 

I tried to debug and found out that the serializer is not getting registered and throwing this stack track - 

````Do not know how to serialize key of type class class com.mypackage.Myclass. Consider implementing a CustomKeySerializer.
org.json4s.package$MappingException: Do not know how to serialize key of type class com.adobe.flamingo.orchestrator.task.JSON. Consider implementing a CustomKeySerializer.
	at org.json4s.reflect.package$.fail(package.scala:95)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:181)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:65)
	at org.json4s.native.Serialization$.write(Serialization.scala:43)
	at org.json4s.native.Serialization$.write(Serialization.scala:37)
	at com.adobe.flamingo.orchestrator.workflow````


I figured out that the error is being thrown from  [here](https://github.com/json4s/json4s/blob/7da6a8458246dadb46fa7fff930823d6bf590d19/core/src/main/scala/org/json4s/Extraction.scala#L181)

I also tried 

MyclassSerializer - 
````class MyclassSerializer extends CustomSerializer[Myclass](format => ( {
  // Impl
}
))
```` 

Can someone please help?

**Comment by shanielh** [comment]
You need to register a key serializer (which serializes your BaseTrait to a simple string) because the map serializer tries to serialize your key as a key of JSON map.

**Comment by magnolia-k** [comment]
@welcomemandeep 
Is the problem solved?
Can I close this issue?
