### ISSUE TITLE
Json4s + Spark serialization problem

### ISSUE THREAD

**Issue by pferrel** [json4s/json4s#496]
### jdk version Java 8

I understand the issue serializing DefaultFormats but thought I had covered the work around below.  I've tried upgrading to 3.5.3 but the same happened in 3.2.x (supplied in Spark 2.2.0). Notice I've put DefaultFormats everywhere I could think of. Some of which I don't think need to be serialized. Did I use the work around correctly? Is there some other fix?

The long JVM exception Spark trace says "unable to serialize task" and points to the line of my code shown below. `ItemID` is a string, `ItemProps` is a `Map[String, Seq[String]]` defined as types in the package object.

Here is the code:

        logger.info(s"Creating an RDD for $actionName")
        implicit val formats = DefaultFormats // serialization work around?
        val itemProps = df.rdd.map[(ItemID, ItemProps)](row => { <--- JVM exception stack points to this line
          implicit val formats = DefaultFormats // serialization work around?
          val itemId = row.getString(0)
          val correlators = row.getSeq[String](1).toList //corrs [22805,22806]
          (itemId, Map(actionName -> JArray(correlators.map { t =>
            implicit val formats = DefaultFormats // serialization work around?
            JsonAST.JString(t)
          })))
        })

Error is the same using Spark 2.2, json4S-native 3.2.x and 3.5.3

    Serialization stack:
	- object not serializable (class: org.json4s.DefaultFormats$, value: org.json4s.DefaultFormats$@7fdd29f3)
	- field (class: com.actionml.URAlgorithm, name: formats, type: class org.json4s.DefaultFormats$)
	- object (class com.actionml.URAlgorithm, com.actionml.URAlgorithm@2dbfa972)
	- field (class: com.actionml.URAlgorithm$$anonfun$udfLLR$1, name: $outer, type: class com.actionml.URAlgorithm)
	- object (class com.actionml.URAlgorithm$$anonfun$udfLLR$1, <function3>)
	- field (class: org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$4, name: func$4, type: interface scala.Function3)
	- object (class org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$4, <function1>)
	- field (class: org.apache.spark.sql.catalyst.expressions.ScalaUDF, name: f, type: interface scala.Function1)
	- object (class org.apache.spark.sql.catalyst.expressions.ScalaUDF, UDF(input[2, bigint, false], input[3, bigint, false], input[5, bigint, false]))
	- element of array (index: 1)
	- array (class [Ljava.lang.Object;, size 3)
	- field (class: org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10, name: references$1, type: class [Ljava.lang.Object;)
	- object (class org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10, <function2>)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:295)
	... 128 more

**Comment by pferrel** [comment]
ping, I've tried all sorts of things here, changing the Spark version, Json4s version, adding imports along with the implicits, everything but downgrading scala to 2.10, which is not an option for me. Any ideas would be greatly appreciated.
