### ISSUE TITLE
"Can't find constructor" thrown from Extraction.decompose() for generic case class and apply() method with different signature than constructor

### ISSUE THREAD

**Issue by pwyczes** [json4s/json4s#507]
### json4s version
3.6.0-M2
### scala version
2.12.4
### jdk version
1.8.0_161

Given generic case class with companion object with apply() function with different signature than constructor breaks Extraction.decompose().

Something like:
```
object GenericCaseClassWithCompanion {
  def apply[A](v: A): GenericCaseClassWithCompanion[A] = GenericCaseClassWithCompanion(v, "Bar")
}
case class GenericCaseClassWithCompanion[A](value: A, other: String)
```
throws following exception:
```
org.json4s.package$MappingException: Can't find constructor for GenericCaseClassWithCompanion
	at org.json4s.reflect.package$.fail(package.scala:95)
	at org.json4s.reflect.ScalaSigReader$.$anonfun$readConstructor$3(ScalaSigReader.scala:21)
	at scala.Option.getOrElse(Option.scala:121)
	at org.json4s.reflect.ScalaSigReader$.readConstructor(ScalaSigReader.scala:21)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:93)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$ctorParamType$3(Reflector.scala:101)
	at scala.collection.immutable.List.map(List.scala:283)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:98)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$createConstructorDescriptors$6(Reflector.scala:153)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$createConstructorDescriptors$3(Reflector.scala:139)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.createConstructorDescriptors(Reflector.scala:133)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.constructorsAndCompanion(Reflector.scala:129)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:180)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:53)
	at org.json4s.reflect.Reflector$.$anonfun$describe$1(Reflector.scala:48)
	at org.json4s.reflect.package$Memo.apply(package.scala:36)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:48)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:119)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:230)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:65)
	at org.json4s.Extraction$.decompose(Extraction.scala:244)
	at org.json4s.ExtractionBugs.$anonfun$new$98(ExtractionBugs.scala:291)
	at org.specs2.matcher.MatchResult$$anon$12.$anonfun$asResult$1(MatchResult.scala:344)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)
	at org.specs2.execute.Result$$anon$11.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.matcher.MatchResult$$anon$12.asResult(MatchResult.scala:344)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.specification.core.AsExecution$$anon$1.$anonfun$execute$1(AsExecution.scala:15)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)
	at org.specs2.execute.Result$$anon$11.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)
	at org.specs2.execute.AsResult$.safely(AsResult.scala:40)
	at org.specs2.specification.core.Execution$.$anonfun$result$1(Execution.scala:305)
	at org.specs2.specification.core.Execution$.$anonfun$withEnvSync$3(Execution.scala:323)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)
	at org.specs2.execute.Result$$anon$11.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)
	at org.specs2.execute.AsResult$.safely(AsResult.scala:40)
	at org.specs2.specification.core.Execution$.$anonfun$withEnvSync$2(Execution.scala:323)
	at org.specs2.specification.core.Execution.$anonfun$startExecution$3(Execution.scala:135)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
My wild guess is that it was introduced with https://github.com/json4s/json4s/pull/487. 
It worked in earlier versions of json4s - 3.3.0.

**Comment by gantamk** [comment]
Facing exactly the same issue.

**Comment by dacr** [comment]
Same for me with : 
```scala
case class CheckedValue[NUM](
  value: NUM,
  isPrime: Boolean,
  digitCount: Long,
  nth: NUM)(implicit numops: Integral[NUM])

object CheckedValue {
  def first[NUM](implicit numops: Integral[NUM]): CheckedValue[NUM] = {
    import numops._
    CheckedValue(value = one + one, isPrime = true, digitCount = 1, nth = one)
  }
  def apply[NUM](value: NUM, isPrime:Boolean, nth:NUM)(implicit numops: Integral[NUM]): CheckedValue[NUM] = {
    CheckedValue(value, isPrime, value.toString.length, nth)
  }
}
```

and `json4s 3.6.9`

raised exception : 
```
org.json4s.package$MappingException: Can't find constructor for CheckedValue
  org.json4s.reflect.package$.fail(package.scala:95)
  org.json4s.reflect.ScalaSigReader$.$anonfun$readConstructor$3(ScalaSigReader.scala:26)
  scala.Option.getOrElse(Option.scala:201)
  org.json4s.reflect.ScalaSigReader$.readConstructor(ScalaSigReader.scala:26)
  org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:93)
  org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$createConstructorDescriptors$7(Reflector.scala:182)
  scala.collection.immutable.ArraySeq.$anonfun$map$1(ArraySeq.scala:71)
  scala.collection.immutable.ArraySeq.$anonfun$map$1$adapted(ArraySeq.scala:71)
  scala.collection.immutable.ArraySeq$.tabulate(ArraySeq.scala:192)
  scala.collection.immutable.ArraySeq$.tabulate(ArraySeq.scala:171)
  scala.collection.ClassTagIterableFactory$AnyIterableDelegate.tabulate(Factory.scala:664)
  scala.collection.immutable.ArraySeq.map(ArraySeq.scala:71)
  scala.collection.immutable.ArraySeq.map(ArraySeq.scala:35)
  org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$createConstructorDescriptors$3(Reflector.scala:164)
  scala.collection.immutable.List.map(List.scala:246)
  scala.collection.immutable.List.map(List.scala:79)
  org.json4s.reflect.Reflector$ClassDescriptorBuilder.createConstructorDescriptors(Reflector.scala:144)
  org.json4s.reflect.Reflector$ClassDescriptorBuilder.constructorsAndCompanion(Reflector.scala:127)
  org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:209)
  org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:53)
  org.json4s.reflect.Reflector$.$anonfun$describe$1(Reflector.scala:48)
  org.json4s.reflect.package$Memo.apply(package.scala:36)
  org.json4s.reflect.Reflector$.describe(Reflector.scala:48)
  org.json4s.Extraction$.decomposeObject$1(Extraction.scala:119)
  org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:231)
  org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:65)
  org.json4s.Extraction$.decompose(Extraction.scala:245)
  ammonite.$file.arangodb$minusprimes$minusfeed$.$anonfun$res_23$1(arangodb-primes-feed.sc:53)
  scala.collection.immutable.LazyList.foreach(LazyList.scala:314)
  ammonite.$file.arangodb$minusprimes$minusfeed$.<clinit>(arangodb-primes-feed.sc:45)
```

**Comment by dacr** [comment]
In fact my issue is a little bit different, after new tests it is related to second implicit arguments list, see : https://github.com/json4s/json4s/issues/702 but may be related

**Comment by nssalian** [comment]
Same issue 
json4s: 3.6.6 Scala 2.12

sbt dependencies:
```
"org.json4s" %% "json4s-jackson" % "3.6.6",
"org.json4s" %% "json4s-native" % "3.6.6"
```
```
org.json4s.package$MappingException: Can't find constructor for <CaseClassName>
	at org.json4s.reflect.package$.fail(package.scala:95)
	at org.json4s.reflect.ScalaSigReader$.$anonfun$readConstructor$3(ScalaSigReader.scala:26)
	at scala.Option.getOrElse(Option.scala:189)
	at org.json4s.reflect.ScalaSigReader$.readConstructor(ScalaSigReader.scala:26)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:93)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$createConstructorDescriptors$7(Reflector.scala:177)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$createConstructorDescriptors$3(Reflector.scala:159)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.createConstructorDescriptors(Reflector.scala:139)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.constructorsAndCompanion(Reflector.scala:135)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:204)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:53)
	at org.json4s.reflect.Reflector$.$anonfun$describe$1(Reflector.scala:48)
	at org.json4s.reflect.package$Memo.apply(package.scala:36)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:48)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:119)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:231)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:65)
	at org.json4s.Extraction$.decompose(Extraction.scala:245)
	at org.json4s.jackson.Serialization$.write(Serialization.scala:22)
	at <classpath>$anonfun$publishToDataHighway$1(<client>.scala:104)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by magnolia-k** [comment]
I haven't written any tests yet, so I can't be sure, but I think the following patch will probably fix it (it doesn't explore the apply method)

core/src/main/scala/org/json4s/reflect/ScalaSigReader.scala

```scala
  def readConstructor(argName: String, clazz: ScalaType, typeArgIndex: Int, argNames: List[String]): Class[_] = {
    val cl = findClass(clazz.erasure)
-    val cstr = findConstructor(cl, argNames).getOrElse(fail("Can't find constructor for " + clazz))
-    findArgType(cstr, argNames.indexOf(argName), typeArgIndex)
+    val cstr = findConstructor(cl, argNames)
+
+    val maybeArgType = cstr map { _ =>
+      findArgType(cstr.get, argNames.indexOf(argName), typeArgIndex)
+    } orElse {
+      val companionClass = findCompanionObject(clazz.erasure)
+      findApply(companionClass, argNames) map { methodSymbol =>
+        findArgType(methodSymbol, argNames.indexOf(argName), typeArgIndex)
+      }
+    }
+
+    maybeArgType.getOrElse(fail("Can't find constructor for " + clazz))
```

**Comment by xuwei-k** [comment]
https://github.com/json4s/json4s/pull/708

**Comment by karenfeng** [comment]
@xuwei-k When can we expect a release with this fix?

**Comment by xuwei-k** [comment]
3.6.10 released
