### ISSUE TITLE
TypeHints + throws AbstractMethodError

### ISSUE THREAD

**Issue by sameerparekh** [json4s/json4s#550]
### jdk version 1.8.0_111

When trying to use `+` on TypeHints in order to create a CompositeTypeHints, I get an AbstractMethodError. 

Here's a repro:

```
package com.twitter.dataproducts.common.workflows.config

import org.json4s.TypeHints

object TypeHintTest extends App {
  val a = new TypeHints {
    override val hints: List[Class[_]] = List.empty
    override def hintFor(clazz: Class[_]): String = ""
    override def classFor(hint: String): Option[Class[_]] = None
  }

  val b = new TypeHints {
    override val hints: List[Class[_]] = List.empty
    override def hintFor(clazz: Class[_]): String = ""
    override def classFor(hint: String): Option[Class[_]] = None
  }

  a + b
}
```

GIves me:

```
Exception in thread "main" java.lang.AbstractMethodError: com.twitter.dataproducts.common.workflows.config.TypeHintTest$$anon$1.org$json4s$TypeHints$$CompositeTypeHints()Lorg/json4s/TypeHints$CompositeTypeHints$;
	at org.json4s.TypeHints$class.$plus(Formats.scala:257)
	at com.twitter.dataproducts.common.workflows.config.TypeHintTest$$anon$1.$plus(TypeHintTest.scala:6)
	at com.twitter.dataproducts.common.workflows.config.TypeHintTest$.delayedEndpoint$com$twitter$dataproducts$common$workflows$config$TypeHintTest$1(TypeHintTest.scala:18)
	at com.twitter.dataproducts.common.workflows.config.TypeHintTest$delayedInit$body.apply(TypeHintTest.scala:5)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.twitter.dataproducts.common.workflows.config.TypeHintTest$.main(TypeHintTest.scala:5)
	at com.twitter.dataproducts.common.workflows.config.TypeHintTest.main(TypeHintTest.scala)
```

**Comment by magnolia-k** [comment]
@xuwei-k 

Should private [TypeHints] be deleted?

```scala
-  private[TypeHints] case class CompositeTypeHints(override val components: List[TypeHints]) extends TypeHints {
+  case class CompositeTypeHints(override val components: List[TypeHints]) extends TypeHints {
```

**Comment by xuwei-k** [comment]
I think `private[TypeHints]` doesn't matter. This is a scala compiler bug 😢 

https://github.com/scala/bug/issues/9948

**Comment by xuwei-k** [comment]
https://github.com/json4s/json4s/pull/606

**Comment by magnolia-k** [comment]
oh...

**Comment by xuwei-k** [comment]
3.6.7 released
