### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/json4s/JsonMethods$class

### ISSUE THREAD

**Issue by widon1104** [json4s/json4s#555]
### json4s version
      3.2.11
### scala version
     2.11.8
### jdk version
     1.8
My little program just use hiveContext.sql to create a table:

```
 hiveContext.sql("CREATE TABLE IF NOT EXISTS sales ("
                + "product STRING,"
                + "category STRING,"
                + "revenue BIGINT)");
```

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/json4s/JsonMethods$class
	at org.json4s.jackson.JsonMethods$.<init>(JsonMethods.scala:50)
	at org.json4s.jackson.JsonMethods$.<clinit>(JsonMethods.scala)
	at org.apache.spark.sql.types.DataType.json(DataType.scala:58)
	at org.apache.spark.sql.hive.HiveExternalCatalog.org$apache$spark$sql$hive$HiveExternalCatalog$$tableMetaToTableProps(HiveExternalCatalog.scala:375)
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$createTable$1.apply$mcV$sp(HiveExternalCatalog.scala:228)
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$createTable$1.apply(HiveExternalCatalog.scala:191)
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$createTable$1.apply(HiveExternalCatalog.scala:191)
	at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:95)
	at org.apache.spark.sql.hive.HiveExternalCatalog.createTable(HiveExternalCatalog.scala:191)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalog.createTable(SessionCatalog.scala:248)
	at org.apache.spark.sql.execution.command.CreateTableCommand.run(tables.scala:116)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:87)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:87)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:185)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:592)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:699)
	at cn.spark.study.sql.RowNumberWindowFunction.main(RowNumberWindowFunction.java:27)
```

**Comment by magnolia-k** [comment]
@widon1104 

This information is difficult to analyze.

Have you confirmed the necessary library import?

**Comment by mccartney** [comment]
Closing the outdated aissue as not enough information was reported.
