### ISSUE TITLE
java.lang.NoSuchMethodError: org.json4s.JsonAST$JBool$.False()Lorg/json4s/JsonAST$JBool

### ISSUE THREAD

**Issue by VictorZan** [json4s/json4s#628]
### json4s version
3.5.3
### scala version
2.11.8
### jdk version
1.8
### spark version
2.4.3

hey,guys,i run json4s on spark 2.0 is ok,but spark 2.4.3 has this error :

```
java.lang.NoSuchMethodError: org.json4s.JsonAST$JBool$.False()Lorg/json4s/JsonAST$JBool;
 at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:26)
 at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:46)
 at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:39)
 at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:32)
 at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:46)
 at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:39)
 at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:46)
 at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:39)
 at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1626)
 at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1220)
 at org.json4s.jackson.JsonMethods$class.parse(JsonMethods.scala:25)
 at org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:55)
```

**Comment by magnolia-k** [comment]
@VictorZan 

Please tell me the version of Json4s used in spark 2.0

**Comment by bbdrlancy** [comment]
json4s version 3.5.3
scala version  2.11.12
jdk version 1.8
spark version 2.4.4
ERROR：java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse$default$3()Z

json4s version 3.2.10
scala version  2.11.12
jdk version 1.8
spark version 2.3.2
It is ok on those version

**Comment by fbocse** [comment]
@bbdrlancy did you happen to find a solution for this problem?

**Comment by magnolia-k** [comment]
Due to the following commit, the method of creating JBool objects has been changed in Json4s 3.3.x and later.

https://github.com/json4s/json4s/commit/c950fc5a332e419afda40277dd9d7dc929c0bc64

Therefore, binary compatibility has been lost.

However, in Spark 2.4.3, Json4s 3.5.3 is specified, and there should be no version inconsistency.

Do you still have old Json4s in your classpath?
Please check it.
