### ISSUE TITLE
Extraction.unflatten() will throw MatchError when field name is prefix of the other field name.

### ISSUE THREAD

**Issue by Wosin** [json4s/json4s#638]
### json4s version
3.6.7
### scala version
2.11.11
### jdk version
AdoptOpenJDK 1.8

I have noticed a probable bug  when trying to call `Extraction.unflatten()`. When we will call `unflatten` on previously flatenned JSON string in situtation where name of one field is prefix of the other fields name. So, let's say we have the following JSON :
```
{"data" : 5, "data_type": 6} 
```
If we will `flatten` this and then try to `unflatten`, it will throw `MatchError`. The same will happen if  instead of `data_type` we will have `data2`, `datad` or any kind of shated prefix. The exception for the descibed case is :
```
Caused by: scala.MatchError: _type (of class java.lang.String)
	at org.json4s.Extraction$$anonfun$unflatten$1.apply(Extraction.scala:351)
	at org.json4s.Extraction$$anonfun$unflatten$1.apply(Extraction.scala:350)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.json4s.Extraction$.unflatten(Extraction.scala:350)
	at org.json4s.Extraction$$anonfun$unflatten$1.apply(Extraction.scala:354)
	at org.json4s.Extraction$$anonfun$unflatten$1.apply(Extraction.scala:350)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.json4s.Extraction$.unflatten(Extraction.scala:350)
	at org.json4s.Extraction$$anonfun$unflatten$1.apply(Extraction.scala:354)
	at org.json4s.Extraction$$anonfun$unflatten$1.apply(Extraction.scala:350)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.json4s.Extraction$.unflatten(Extraction.scala:350)
	at org.json4s.Extraction$$anonfun$unflatten$1.apply(Extraction.scala:354)
	at org.json4s.Extraction$$anonfun$unflatten$1.apply(Extraction.scala:350)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.json4s.Extraction$.unflatten(Extraction.scala:350)
```

**Comment by magnolia-k** [comment]
The above event has occurred because the code that identifies the following key is simply determined by `startsWith`.

https://github.com/json4s/json4s/blob/e776c4e639860439b5d6ad52a87e5df95f6a9bf9/core/src/main/scala/org/json4s/Extraction.scala#L333-L336

**Comment by magnolia-k** [comment]
made PR

https://github.com/json4s/json4s/pull/644
