### ISSUE TITLE
NoSuchMethodException while extracting in scala 2.13.1

### ISSUE THREAD

**Issue by cchafer** [json4s/json4s#659]
### jdk version: Java HotSpot(TM) 64-Bit Server VM 11.0.5+10-LTS

I'm currently moving my project from scala 2.12._ to 2.13.1.
After a few modifications, everything compiles just fine, but at runtime, Json4s throws an exception when I try to extract case classes from Json.

When I first had the problem, the exception was stating that Vector$.apply(scala.collection.Seq) was not a valid method.
I solved my problem by creating a custom Vector[_] serializer, as stated in this (quite old) bug: https://github.com/json4s/json4s/issues/82.
It worked, and so I tried to go a little further.
At this time, I get a new exception while trying to extract values from a custom API server (client code generated with swagger-codegen).

The exception is:
```
java.lang.NoSuchMethodException: scala.collection.immutable.Seq$.apply(scala.collection.Seq)
	at java.base/java.lang.Class.getMethod(Class.java:2108)
	at org.json4s.Extraction$CollectionBuilder.reflMethod$Method1(Extraction.scala:476)
	at org.json4s.Extraction$CollectionBuilder.$anonfun$result$9(Extraction.scala:476)
	at org.json4s.Extraction$CollectionBuilder.mkCollection(Extraction.scala:437)
	at org.json4s.Extraction$CollectionBuilder.result(Extraction.scala:476)
	at org.json4s.Extraction$.$anonfun$extract$9(Extraction.scala:392)
	at org.json4s.Extraction$.$anonfun$customOrElse$1(Extraction.scala:658)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
	at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:339)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:658)
	at org.json4s.Extraction$.extract(Extraction.scala:392)
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:554)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$3.applyOrElse(Extraction.scala:593)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$3.applyOrElse(Extraction.scala:591)
	at scala.collection.StrictOptimizedIterableOps.collect(StrictOptimizedIterableOps.scala:151)
	at scala.collection.StrictOptimizedIterableOps.collect$(StrictOptimizedIterableOps.scala:136)
	at scala.collection.immutable.ArraySeq.collect(ArraySeq.scala:35)
	at org.json4s.Extraction$ClassInstanceBuilder.instantiate(Extraction.scala:591)
	at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:651)
	at org.json4s.Extraction$.$anonfun$extract$10(Extraction.scala:410)
	at org.json4s.Extraction$.$anonfun$customOrElse$1(Extraction.scala:658)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
	at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:339)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:658)
	at org.json4s.Extraction$.extract(Extraction.scala:402)
	at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:554)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$3.applyOrElse(Extraction.scala:593)
	at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$3.applyOrElse(Extraction.scala:591)
	at scala.collection.StrictOptimizedIterableOps.collect(StrictOptimizedIterableOps.scala:151)
	at scala.collection.StrictOptimizedIterableOps.collect$(StrictOptimizedIterableOps.scala:136)
	at scala.collection.immutable.ArraySeq.collect(ArraySeq.scala:35)
	at org.json4s.Extraction$ClassInstanceBuilder.instantiate(Extraction.scala:591)
	at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:651)
	at org.json4s.Extraction$.$anonfun$extract$10(Extraction.scala:410)
	at org.json4s.Extraction$.$anonfun$customOrElse$1(Extraction.scala:658)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
	at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:339)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:658)
	at org.json4s.Extraction$.extract(Extraction.scala:402)
	at org.json4s.Extraction$.extract(Extraction.scala:40)
	... 20 common frames omitted
```

My model is: 
```
case class Account (
  id: Long,
  login: String,
  nickname: Option[String],
  security: Seq[Security]
)

object Account {
  type Security = Security.Value
  object Security extends Enumeration {
    val SHIELD = Value("SHIELD")
    val AUTHENTICATOR = Value("AUTHENTICATOR")
  }
}
```

And the input json is: 
```
{"id":8,"login":"kam","nickname":"[kam]","security":[]}
```

I'm quite sure adding a custom serializer for Seq is not a good idea :D
Am i missing something ?

Camille

**Comment by cchafer** [comment]
After a few hours of test/debug, I found the reason. I Close this issue, and open a new, more specific one.

**Comment by seveneves** [comment]
@cchafer It would have been nice to have a link to this more specific issue.
