### ISSUE TITLE
Mapping Exception encountered when using RichSerializer with type hints

### ISSUE THREAD

**Issue by asantas93** [json4s/json4s#689]
Given
```scala
trait SomeTrait
case class HashMapHaver(map: HashMap[String, Option[Int]]) extends SomeTrait
object HashMapDeserializer extends RichSerializer[HashMap[String, _]] {

  override def deserialize(implicit format: Formats): PartialFunction[(ScalaType, JValue), HashMap[String, _]] = {
    case (scalaType, JObject(fields)) if classOf[HashMap[_, _]] == scalaType.erasure =>
      scalaType.manifest.typeArguments match {
        case List(_, vType) =>
          HashMap(
            fields.map {
              case (k, v) => k -> extract(v)(format, vType)
            }: _*
          )
      }
  }

  override def serialize(implicit format: Formats): PartialFunction[Any, JValue] = {
    case map: HashMap[_, _] =>
      JObject {
        map.map {
          case (k: String, v) => k -> decompose(v)
          case (k, _) => throw new MappingException(s"Expected String key but got $k")
        }.toList
      }
  }
}

```
The first test passes, but the second fails
```scala
    "deserialize hash maps correctly" in {
      implicit val formats: Formats = DefaultFormats + HashMapDeserializer
      val json = """{"map":{"foo": null, "bar": 2}}"""
      val extracted = JsonMethods.parse(json).extract[HashMapHaver]
      extracted shouldEqual HashMapHaver(HashMap("foo" -> None, "bar" -> Some(2)))
    }

    "be compatible with type hints" in {
      implicit val formats: Formats = DefaultFormats.withTypeHintFieldName("hint") + HashMapDeserializer + MappedTypeHints(Map(classOf[HashMapHaver] -> "map_haver"))
      val json = """{"map":{"foo": null, "bar": 2}, "hint": "map_haver"}"""
      val extracted = JsonMethods.parse(json).extract[SomeTrait]
      extracted shouldEqual HashMapHaver(HashMap("foo" -> None, "bar" -> Some(2)))
    }
```
```scala
org.json4s.package$MappingException: Parsed JSON values do not match with class constructor
args=Map(foo -> None, bar -> Some(2))
arg types=scala.collection.immutable.Map$Map2
executable=Executable(Constructor(public org.json4s.HashMapHaver(scala.collection.immutable.HashMap)))
cause=argument type mismatch
types comparison result=scala.collection.immutable.Map$Map2(sun.misc.Launcher$AppClassLoader@18b4aac2) !<: scala.collection.immutable.HashMap(sun.misc.Launcher$AppClassLoader@18b4aac2)
org.json4s.package$MappingException: Parsed JSON values do not match with class constructor
args=Map(foo -> None, bar -> Some(2))
arg types=scala.collection.immutable.Map$Map2
executable=Executable(Constructor(public org.json4s.HashMapHaver(scala.collection.immutable.HashMap)))
cause=argument type mismatch
types comparison result=scala.collection.immutable.Map$Map2(sun.misc.Launcher$AppClassLoader@18b4aac2) !<: scala.collection.immutable.HashMap(sun.misc.Launcher$AppClassLoader@18b4aac2)
	at org.json4s.reflect.package$.fail(package.scala:95)
	at org.json4s.Extraction$ClassInstanceBuilder.instantiate(Extraction.scala:632)
	at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:656)
	at org.json4s.Extraction$.$anonfun$extract$10(Extraction.scala:418)
	at org.json4s.Extraction$.$anonfun$customOrElse$1(Extraction.scala:667)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
	at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:257)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:667)
	at org.json4s.Extraction$.extract(Extraction.scala:410)
	at org.json4s.Extraction$ClassInstanceBuilder.mkWithTypeHint(Extraction.scala:646)
	at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:655)
	at org.json4s.Extraction$.$anonfun$extract$10(Extraction.scala:418)
	at org.json4s.Extraction$.$anonfun$customOrElse$1(Extraction.scala:667)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
	at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:257)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:667)
	at org.json4s.Extraction$.extract(Extraction.scala:410)
	at org.json4s.Extraction$.extract(Extraction.scala:42)
	at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
	at org.json4s.RichSerializerTest.$anonfun$new$10(RichSerializerTest.scala:81)
	at org.specs2.matcher.MatchResult$$anon$12.$anonfun$asResult$1(MatchResult.scala:353)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:124)
	at org.specs2.execute.Result$$anon$4.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.matcher.MatchResult$$anon$12.asResult(MatchResult.scala:353)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.specification.core.AsExecution$$anon$1.$anonfun$execute$1(AsExecution.scala:17)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:124)
	at org.specs2.execute.Result$$anon$4.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:124)
	at org.specs2.execute.AsResult$.safely(AsResult.scala:40)
	at org.specs2.specification.core.Execution$.$anonfun$result$1(Execution.scala:345)
	at org.specs2.specification.core.Execution$.$anonfun$withEnvSync$3(Execution.scala:363)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:124)
	at org.specs2.execute.Result$$anon$4.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:124)
	at org.specs2.execute.AsResult$.safely(AsResult.scala:40)
	at org.specs2.specification.core.Execution$.$anonfun$withEnvSync$2(Execution.scala:363)
	at org.specs2.specification.core.Execution.$anonfun$startExecution$3(Execution.scala:143)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The cause of this exception appears to be an `IllegalArgumentException` thrown by https://github.com/json4s/json4s/blob/6e35de05384093d7cfe0fd97fc0047f05c5bbc35/core/src/main/scala/org/json4s/reflect/Executable.scala#L54

### json4s version
3.7.0-M4
### scala version
2.12.8
### jdk version
8

**Comment by asantas93** [comment]
I'm trying to figure this one out but am reporting it here in case someone has any ideas about why the result with type hints would be different. @magnolia-k @seratch

**Comment by asantas93** [comment]
Relates to https://github.com/json4s/json4s/issues/631

**Comment by asantas93** [comment]
Opened PR with fix: https://github.com/json4s/json4s/pull/690

**Comment by magnolia-k** [comment]
The issue itself seems to be good to close since the PR has been merged

Also, whether or not to backport to 3.6.x is a separate discussion.
