### ISSUE TITLE
json4s-jackson-core on Scala3: MatchError: StringInput({})

### ISSUE THREAD

**Issue by thesamet** [json4s/json4s#814]
### json4s version
4.0.0

### scala version
3.0.0

### jdk version
16

Vanilla Scala project:
build.sbt

```scala
val scala3Version = "3.0.0"

lazy val root = project
  .in(file("."))
  .settings(
    name := "scala3-simple",
    version := "0.1.0",

    scalaVersion := scala3Version,

    libraryDependencies ++= Seq(
      "com.novocode" % "junit-interface" % "0.11" % "test",
      "org.json4s" %% "json4s-jackson-core" % "4.0.0"
    )
  )
```

src/main/scala/Main.scala:
```scala
import org.json4s.jackson.JsonMethods._

@main def hello: Unit =
  parse("{}")
```

when running the code I get:
```
[error] (run-main-2) scala.MatchError: StringInput({}) (of class org.json4s.StringInput)
[error] scala.MatchError: StringInput({}) (of class org.json4s.StringInput)
[error] 	at org.json4s.jackson.JsonMethods.parse(JsonMethods.scala:41)
[error] 	at org.json4s.jackson.JsonMethods.parse$(JsonMethods.scala:10)
[error] 	at org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:83)
[error] 	at Main$package$.hello(Main.scala:4)
[error] 	at hello.main(Main.scala:3)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
```

Note that I verified that the call to `parse()` works when using Scala 2 (and updating the syntax accordingly)

**Comment by xuwei-k** [comment]
😭 

- https://github.com/lampepfl/dotty/issues/12976
- https://github.com/json4s/json4s/blob/c3aa862a80d524d9e1cd4dda9d35e8329e6fd5ed/jackson-core/src/main/scala/org/json4s/jackson/JsonMethods.scala#L37-L42
- https://github.com/FasterXML/jackson-databind/blob/4586213075f7944eb797c008c95715621b720b42/src/main/java/com/fasterxml/jackson/databind/ObjectReader.java#L1486

**Comment by thesamet** [comment]
Thanks for implementing this workaround here!
