### ISSUE TITLE
Mapping exception

### ISSUE THREAD

**Issue by Fuzion24** [json4s/json4s#83]
I am using version 3.2.6 and scala 2.10.3..
This does not occur on older versions of json4s

```
org.json4s.package$MappingException: Can't find ScalaSig for class java.lang.Object
    at org.json4s.reflect.ScalaSigReader$.findClass(ScalaSigReader.scala:42)
    at org.json4s.reflect.ScalaSigReader$.org$json4s$reflect$ScalaSigReader$$read$1(ScalaSigReader.scala:36)
    at org.json4s.reflect.ScalaSigReader$.org$json4s$reflect$ScalaSigReader$$read$1(ScalaSigReader.scala:36)
    at org.json4s.reflect.ScalaSigReader$.readField(ScalaSigReader.scala:38)
    at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:66)
    at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:65)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.json4s.reflect.Reflector$ClassDescriptorBuilder.fields(Reflector.scala:65)
    at org.json4s.reflect.Reflector$ClassDescriptorBuilder.properties(Reflector.scala:82)
    at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:159)
    at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:50)
    at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
    at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
    at org.json4s.reflect.package$Memo.apply(package.scala:39)
    at org.json4s.reflect.Reflector$.describe(Reflector.scala:44)
    at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:140)
    at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:114)
    at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:67)
    at org.json4s.native.Serialization$.write(Serialization.scala:44)
    at org.json4s.native.Serialization$.write(Serialization.scala:38)
```

**Comment by raimohanska** [comment]
Could you elaborate on the version mismatch? What is actually wrong?

I'm using Maven and cannot use your SBT magic :)

**Comment by raimohanska** [comment]
Oh, in fact there was more info in the log:

org.json4s.package$MappingException: No usable value for kieli
25-Feb-2015 10:33:27	No usable value for $outer
25-Feb-2015 10:33:27	Can't find ScalaSig for class java.lang.Object

Turned out to be a serialization problem with Enums in case the input value was not a valid enum value. We are using EnumNameSerializer here. I think the error message could be better of course.

**Comment by magnolia-k** [comment]
The problem itself seems to be solved so close it. Please raise an issue again if you have any other problems.
